import { listConversationMessages, sendConversationMessage } from "@/shared/api/generated";
import type { Message, MessagesResponse } from "@/shared/api/generated";
import { authorizedHeaders, correlated, dateTime, exact, fail, requestID, requestIDHeader, sessionToken, unavailable, uuid } from "@/features/messaging/protected-bff";

export const runtime="nodejs";type RouteContext={params:Promise<{conversationId:string}>};
export async function GET(request:Request,context:RouteContext):Promise<Response>{const id=requestID(request.headers),token=await sessionToken(),{conversationId}=await context.params;if(!token)return fail("UNAUTHORIZED","Unauthorized",401,id);if(!uuid(conversationId))return fail("INVALID_REQUEST","Invalid request",400,id);const baseUrl=process.env.JUNTLY_API_ORIGIN;if(!baseUrl)return unavailable(id);try{const upstream=await listConversationMessages({baseUrl,path:{conversationId},headers:authorizedHeaders(token,id)});if(upstream.error||!upstream.response?.ok||!correlated(upstream.response,id)||!validList(upstream.data))return unavailable(id);return Response.json(upstream.data,{status:200,headers:{[requestIDHeader]:id}})}catch{return unavailable(id)}}
export async function POST(request:Request,context:RouteContext):Promise<Response>{const id=requestID(request.headers),token=await sessionToken(),{conversationId}=await context.params;if(!token)return fail("UNAUTHORIZED","Unauthorized",401,id);let value:unknown;try{value=JSON.parse(await request.text())}catch{return fail("INVALID_REQUEST","Invalid request",400,id)};if(!uuid(conversationId)||!exact(value,["body"])||typeof value.body!=="string"||value.body.trim().length<1||value.body.length>4000)return fail("INVALID_REQUEST","Invalid request",400,id);const baseUrl=process.env.JUNTLY_API_ORIGIN;if(!baseUrl)return unavailable(id);try{const upstream=await sendConversationMessage({baseUrl,path:{conversationId},body:{body:value.body.trim()},headers:authorizedHeaders(token,id)});if(upstream.error||upstream.response?.status!==201||!correlated(upstream.response,id)||!validMessage(upstream.data))return unavailable(id);return Response.json(upstream.data,{status:201,headers:{[requestIDHeader]:id}})}catch{return unavailable(id)}}
function validList(value:MessagesResponse|undefined):value is MessagesResponse{return !!value&&exact(value,["messages"])&&Array.isArray(value.messages)&&value.messages.every(validMessage)}
function validMessage(value:Message|undefined):value is Message{return !!value&&exact(value,["id","conversationId","senderId","body","createdAt"])&&uuid(value.id)&&uuid(value.conversationId)&&uuid(value.senderId)&&typeof value.body==="string"&&value.body.length>0&&value.body.length<=4000&&dateTime(value.createdAt)}
