// Code generated by ent, DO NOT EDIT.

package listingmedia

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the listingmedia type in the database.
	Label = "listing_media"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldListingID holds the string denoting the listing_id field in the database.
	FieldListingID = "listing_id"
	// FieldOrdinal holds the string denoting the ordinal field in the database.
	FieldOrdinal = "ordinal"
	// FieldContentType holds the string denoting the content_type field in the database.
	FieldContentType = "content_type"
	// FieldByteSize holds the string denoting the byte_size field in the database.
	FieldByteSize = "byte_size"
	// FieldChecksumSha256 holds the string denoting the checksum_sha256 field in the database.
	FieldChecksumSha256 = "checksum_sha256"
	// FieldObjectReference holds the string denoting the object_reference field in the database.
	FieldObjectReference = "object_reference"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the listingmedia in the database.
	Table = "listing_media"
)

// Columns holds all SQL columns for listingmedia fields.
var Columns = []string{
	FieldID,
	FieldListingID,
	FieldOrdinal,
	FieldContentType,
	FieldByteSize,
	FieldChecksumSha256,
	FieldObjectReference,
	FieldState,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OrdinalValidator is a validator for the "ordinal" field. It is called by the builders before save.
	OrdinalValidator func(int) error
	// ContentTypeValidator is a validator for the "content_type" field. It is called by the builders before save.
	ContentTypeValidator func(string) error
	// ByteSizeValidator is a validator for the "byte_size" field. It is called by the builders before save.
	ByteSizeValidator func(int64) error
	// ChecksumSha256Validator is a validator for the "checksum_sha256" field. It is called by the builders before save.
	ChecksumSha256Validator func(string) error
	// ObjectReferenceValidator is a validator for the "object_reference" field. It is called by the builders before save.
	ObjectReferenceValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// State defines the type for the "state" enum field.
type State string

// StatePendingUpload is the default value of the State enum.
const DefaultState = StatePendingUpload

// State values.
const (
	StatePendingUpload State = "pending_upload"
	StateReady         State = "ready"
	StateDeleted       State = "deleted"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StatePendingUpload, StateReady, StateDeleted:
		return nil
	default:
		return fmt.Errorf("listingmedia: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the ListingMedia queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByListingID orders the results by the listing_id field.
func ByListingID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldListingID, opts...).ToFunc()
}

// ByOrdinal orders the results by the ordinal field.
func ByOrdinal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrdinal, opts...).ToFunc()
}

// ByContentType orders the results by the content_type field.
func ByContentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentType, opts...).ToFunc()
}

// ByByteSize orders the results by the byte_size field.
func ByByteSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldByteSize, opts...).ToFunc()
}

// ByChecksumSha256 orders the results by the checksum_sha256 field.
func ByChecksumSha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChecksumSha256, opts...).ToFunc()
}

// ByObjectReference orders the results by the object_reference field.
func ByObjectReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObjectReference, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
