// Code generated by ent, DO NOT EDIT.

package listingmedia

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLTE(FieldID, id))
}

// ListingID applies equality check predicate on the "listing_id" field. It's identical to ListingIDEQ.
func ListingID(v uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldListingID, v))
}

// Ordinal applies equality check predicate on the "ordinal" field. It's identical to OrdinalEQ.
func Ordinal(v int) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldOrdinal, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldContentType, v))
}

// ByteSize applies equality check predicate on the "byte_size" field. It's identical to ByteSizeEQ.
func ByteSize(v int64) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldByteSize, v))
}

// ChecksumSha256 applies equality check predicate on the "checksum_sha256" field. It's identical to ChecksumSha256EQ.
func ChecksumSha256(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldChecksumSha256, v))
}

// ObjectReference applies equality check predicate on the "object_reference" field. It's identical to ObjectReferenceEQ.
func ObjectReference(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldObjectReference, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldUpdatedAt, v))
}

// ListingIDEQ applies the EQ predicate on the "listing_id" field.
func ListingIDEQ(v uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldListingID, v))
}

// ListingIDNEQ applies the NEQ predicate on the "listing_id" field.
func ListingIDNEQ(v uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNEQ(FieldListingID, v))
}

// ListingIDIn applies the In predicate on the "listing_id" field.
func ListingIDIn(vs ...uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldIn(FieldListingID, vs...))
}

// ListingIDNotIn applies the NotIn predicate on the "listing_id" field.
func ListingIDNotIn(vs ...uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNotIn(FieldListingID, vs...))
}

// ListingIDGT applies the GT predicate on the "listing_id" field.
func ListingIDGT(v uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGT(FieldListingID, v))
}

// ListingIDGTE applies the GTE predicate on the "listing_id" field.
func ListingIDGTE(v uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGTE(FieldListingID, v))
}

// ListingIDLT applies the LT predicate on the "listing_id" field.
func ListingIDLT(v uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLT(FieldListingID, v))
}

// ListingIDLTE applies the LTE predicate on the "listing_id" field.
func ListingIDLTE(v uuid.UUID) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLTE(FieldListingID, v))
}

// OrdinalEQ applies the EQ predicate on the "ordinal" field.
func OrdinalEQ(v int) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldOrdinal, v))
}

// OrdinalNEQ applies the NEQ predicate on the "ordinal" field.
func OrdinalNEQ(v int) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNEQ(FieldOrdinal, v))
}

// OrdinalIn applies the In predicate on the "ordinal" field.
func OrdinalIn(vs ...int) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldIn(FieldOrdinal, vs...))
}

// OrdinalNotIn applies the NotIn predicate on the "ordinal" field.
func OrdinalNotIn(vs ...int) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNotIn(FieldOrdinal, vs...))
}

// OrdinalGT applies the GT predicate on the "ordinal" field.
func OrdinalGT(v int) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGT(FieldOrdinal, v))
}

// OrdinalGTE applies the GTE predicate on the "ordinal" field.
func OrdinalGTE(v int) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGTE(FieldOrdinal, v))
}

// OrdinalLT applies the LT predicate on the "ordinal" field.
func OrdinalLT(v int) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLT(FieldOrdinal, v))
}

// OrdinalLTE applies the LTE predicate on the "ordinal" field.
func OrdinalLTE(v int) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLTE(FieldOrdinal, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldContainsFold(FieldContentType, v))
}

// ByteSizeEQ applies the EQ predicate on the "byte_size" field.
func ByteSizeEQ(v int64) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldByteSize, v))
}

// ByteSizeNEQ applies the NEQ predicate on the "byte_size" field.
func ByteSizeNEQ(v int64) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNEQ(FieldByteSize, v))
}

// ByteSizeIn applies the In predicate on the "byte_size" field.
func ByteSizeIn(vs ...int64) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldIn(FieldByteSize, vs...))
}

// ByteSizeNotIn applies the NotIn predicate on the "byte_size" field.
func ByteSizeNotIn(vs ...int64) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNotIn(FieldByteSize, vs...))
}

// ByteSizeGT applies the GT predicate on the "byte_size" field.
func ByteSizeGT(v int64) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGT(FieldByteSize, v))
}

// ByteSizeGTE applies the GTE predicate on the "byte_size" field.
func ByteSizeGTE(v int64) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGTE(FieldByteSize, v))
}

// ByteSizeLT applies the LT predicate on the "byte_size" field.
func ByteSizeLT(v int64) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLT(FieldByteSize, v))
}

// ByteSizeLTE applies the LTE predicate on the "byte_size" field.
func ByteSizeLTE(v int64) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLTE(FieldByteSize, v))
}

// ChecksumSha256EQ applies the EQ predicate on the "checksum_sha256" field.
func ChecksumSha256EQ(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldChecksumSha256, v))
}

// ChecksumSha256NEQ applies the NEQ predicate on the "checksum_sha256" field.
func ChecksumSha256NEQ(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNEQ(FieldChecksumSha256, v))
}

// ChecksumSha256In applies the In predicate on the "checksum_sha256" field.
func ChecksumSha256In(vs ...string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldIn(FieldChecksumSha256, vs...))
}

// ChecksumSha256NotIn applies the NotIn predicate on the "checksum_sha256" field.
func ChecksumSha256NotIn(vs ...string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNotIn(FieldChecksumSha256, vs...))
}

// ChecksumSha256GT applies the GT predicate on the "checksum_sha256" field.
func ChecksumSha256GT(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGT(FieldChecksumSha256, v))
}

// ChecksumSha256GTE applies the GTE predicate on the "checksum_sha256" field.
func ChecksumSha256GTE(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGTE(FieldChecksumSha256, v))
}

// ChecksumSha256LT applies the LT predicate on the "checksum_sha256" field.
func ChecksumSha256LT(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLT(FieldChecksumSha256, v))
}

// ChecksumSha256LTE applies the LTE predicate on the "checksum_sha256" field.
func ChecksumSha256LTE(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLTE(FieldChecksumSha256, v))
}

// ChecksumSha256Contains applies the Contains predicate on the "checksum_sha256" field.
func ChecksumSha256Contains(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldContains(FieldChecksumSha256, v))
}

// ChecksumSha256HasPrefix applies the HasPrefix predicate on the "checksum_sha256" field.
func ChecksumSha256HasPrefix(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldHasPrefix(FieldChecksumSha256, v))
}

// ChecksumSha256HasSuffix applies the HasSuffix predicate on the "checksum_sha256" field.
func ChecksumSha256HasSuffix(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldHasSuffix(FieldChecksumSha256, v))
}

// ChecksumSha256EqualFold applies the EqualFold predicate on the "checksum_sha256" field.
func ChecksumSha256EqualFold(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEqualFold(FieldChecksumSha256, v))
}

// ChecksumSha256ContainsFold applies the ContainsFold predicate on the "checksum_sha256" field.
func ChecksumSha256ContainsFold(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldContainsFold(FieldChecksumSha256, v))
}

// ObjectReferenceEQ applies the EQ predicate on the "object_reference" field.
func ObjectReferenceEQ(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldObjectReference, v))
}

// ObjectReferenceNEQ applies the NEQ predicate on the "object_reference" field.
func ObjectReferenceNEQ(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNEQ(FieldObjectReference, v))
}

// ObjectReferenceIn applies the In predicate on the "object_reference" field.
func ObjectReferenceIn(vs ...string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldIn(FieldObjectReference, vs...))
}

// ObjectReferenceNotIn applies the NotIn predicate on the "object_reference" field.
func ObjectReferenceNotIn(vs ...string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNotIn(FieldObjectReference, vs...))
}

// ObjectReferenceGT applies the GT predicate on the "object_reference" field.
func ObjectReferenceGT(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGT(FieldObjectReference, v))
}

// ObjectReferenceGTE applies the GTE predicate on the "object_reference" field.
func ObjectReferenceGTE(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGTE(FieldObjectReference, v))
}

// ObjectReferenceLT applies the LT predicate on the "object_reference" field.
func ObjectReferenceLT(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLT(FieldObjectReference, v))
}

// ObjectReferenceLTE applies the LTE predicate on the "object_reference" field.
func ObjectReferenceLTE(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLTE(FieldObjectReference, v))
}

// ObjectReferenceContains applies the Contains predicate on the "object_reference" field.
func ObjectReferenceContains(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldContains(FieldObjectReference, v))
}

// ObjectReferenceHasPrefix applies the HasPrefix predicate on the "object_reference" field.
func ObjectReferenceHasPrefix(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldHasPrefix(FieldObjectReference, v))
}

// ObjectReferenceHasSuffix applies the HasSuffix predicate on the "object_reference" field.
func ObjectReferenceHasSuffix(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldHasSuffix(FieldObjectReference, v))
}

// ObjectReferenceEqualFold applies the EqualFold predicate on the "object_reference" field.
func ObjectReferenceEqualFold(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEqualFold(FieldObjectReference, v))
}

// ObjectReferenceContainsFold applies the ContainsFold predicate on the "object_reference" field.
func ObjectReferenceContainsFold(v string) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldContainsFold(FieldObjectReference, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNotIn(FieldState, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ListingMedia {
	return predicate.ListingMedia(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ListingMedia) predicate.ListingMedia {
	return predicate.ListingMedia(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ListingMedia) predicate.ListingMedia {
	return predicate.ListingMedia(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ListingMedia) predicate.ListingMedia {
	return predicate.ListingMedia(sql.NotPredicates(p))
}
