// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/administrativearea"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/locality"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/predicate"
	"github.com/google/uuid"
)

// AdministrativeAreaQuery is the builder for querying AdministrativeArea entities.
type AdministrativeAreaQuery struct {
	config
	ctx            *QueryContext
	order          []administrativearea.OrderOption
	inters         []Interceptor
	predicates     []predicate.AdministrativeArea
	withChildren   *AdministrativeAreaQuery
	withParent     *AdministrativeAreaQuery
	withLocalities *LocalityQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AdministrativeAreaQuery builder.
func (_q *AdministrativeAreaQuery) Where(ps ...predicate.AdministrativeArea) *AdministrativeAreaQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AdministrativeAreaQuery) Limit(limit int) *AdministrativeAreaQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AdministrativeAreaQuery) Offset(offset int) *AdministrativeAreaQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AdministrativeAreaQuery) Unique(unique bool) *AdministrativeAreaQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AdministrativeAreaQuery) Order(o ...administrativearea.OrderOption) *AdministrativeAreaQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryChildren chains the current query on the "children" edge.
func (_q *AdministrativeAreaQuery) QueryChildren() *AdministrativeAreaQuery {
	query := (&AdministrativeAreaClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(administrativearea.Table, administrativearea.FieldID, selector),
			sqlgraph.To(administrativearea.Table, administrativearea.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, administrativearea.ChildrenTable, administrativearea.ChildrenColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParent chains the current query on the "parent" edge.
func (_q *AdministrativeAreaQuery) QueryParent() *AdministrativeAreaQuery {
	query := (&AdministrativeAreaClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(administrativearea.Table, administrativearea.FieldID, selector),
			sqlgraph.To(administrativearea.Table, administrativearea.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, administrativearea.ParentTable, administrativearea.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLocalities chains the current query on the "localities" edge.
func (_q *AdministrativeAreaQuery) QueryLocalities() *LocalityQuery {
	query := (&LocalityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(administrativearea.Table, administrativearea.FieldID, selector),
			sqlgraph.To(locality.Table, locality.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, administrativearea.LocalitiesTable, administrativearea.LocalitiesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AdministrativeArea entity from the query.
// Returns a *NotFoundError when no AdministrativeArea was found.
func (_q *AdministrativeAreaQuery) First(ctx context.Context) (*AdministrativeArea, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{administrativearea.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AdministrativeAreaQuery) FirstX(ctx context.Context) *AdministrativeArea {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AdministrativeArea ID from the query.
// Returns a *NotFoundError when no AdministrativeArea ID was found.
func (_q *AdministrativeAreaQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{administrativearea.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AdministrativeAreaQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AdministrativeArea entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AdministrativeArea entity is found.
// Returns a *NotFoundError when no AdministrativeArea entities are found.
func (_q *AdministrativeAreaQuery) Only(ctx context.Context) (*AdministrativeArea, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{administrativearea.Label}
	default:
		return nil, &NotSingularError{administrativearea.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AdministrativeAreaQuery) OnlyX(ctx context.Context) *AdministrativeArea {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AdministrativeArea ID in the query.
// Returns a *NotSingularError when more than one AdministrativeArea ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AdministrativeAreaQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{administrativearea.Label}
	default:
		err = &NotSingularError{administrativearea.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AdministrativeAreaQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AdministrativeAreas.
func (_q *AdministrativeAreaQuery) All(ctx context.Context) ([]*AdministrativeArea, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AdministrativeArea, *AdministrativeAreaQuery]()
	return withInterceptors[[]*AdministrativeArea](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AdministrativeAreaQuery) AllX(ctx context.Context) []*AdministrativeArea {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AdministrativeArea IDs.
func (_q *AdministrativeAreaQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(administrativearea.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AdministrativeAreaQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AdministrativeAreaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AdministrativeAreaQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AdministrativeAreaQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AdministrativeAreaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AdministrativeAreaQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AdministrativeAreaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AdministrativeAreaQuery) Clone() *AdministrativeAreaQuery {
	if _q == nil {
		return nil
	}
	return &AdministrativeAreaQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]administrativearea.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.AdministrativeArea{}, _q.predicates...),
		withChildren:   _q.withChildren.Clone(),
		withParent:     _q.withParent.Clone(),
		withLocalities: _q.withLocalities.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithChildren tells the query-builder to eager-load the nodes that are connected to
// the "children" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AdministrativeAreaQuery) WithChildren(opts ...func(*AdministrativeAreaQuery)) *AdministrativeAreaQuery {
	query := (&AdministrativeAreaClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChildren = query
	return _q
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AdministrativeAreaQuery) WithParent(opts ...func(*AdministrativeAreaQuery)) *AdministrativeAreaQuery {
	query := (&AdministrativeAreaClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withParent = query
	return _q
}

// WithLocalities tells the query-builder to eager-load the nodes that are connected to
// the "localities" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AdministrativeAreaQuery) WithLocalities(opts ...func(*LocalityQuery)) *AdministrativeAreaQuery {
	query := (&LocalityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLocalities = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Source string `json:"source,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AdministrativeArea.Query().
//		GroupBy(administrativearea.FieldSource).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AdministrativeAreaQuery) GroupBy(field string, fields ...string) *AdministrativeAreaGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AdministrativeAreaGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = administrativearea.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Source string `json:"source,omitempty"`
//	}
//
//	client.AdministrativeArea.Query().
//		Select(administrativearea.FieldSource).
//		Scan(ctx, &v)
func (_q *AdministrativeAreaQuery) Select(fields ...string) *AdministrativeAreaSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AdministrativeAreaSelect{AdministrativeAreaQuery: _q}
	sbuild.label = administrativearea.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AdministrativeAreaSelect configured with the given aggregations.
func (_q *AdministrativeAreaQuery) Aggregate(fns ...AggregateFunc) *AdministrativeAreaSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AdministrativeAreaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !administrativearea.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AdministrativeAreaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AdministrativeArea, error) {
	var (
		nodes       = []*AdministrativeArea{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withChildren != nil,
			_q.withParent != nil,
			_q.withLocalities != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AdministrativeArea).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AdministrativeArea{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withChildren; query != nil {
		if err := _q.loadChildren(ctx, query, nodes,
			func(n *AdministrativeArea) { n.Edges.Children = []*AdministrativeArea{} },
			func(n *AdministrativeArea, e *AdministrativeArea) { n.Edges.Children = append(n.Edges.Children, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withParent; query != nil {
		if err := _q.loadParent(ctx, query, nodes, nil,
			func(n *AdministrativeArea, e *AdministrativeArea) { n.Edges.Parent = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLocalities; query != nil {
		if err := _q.loadLocalities(ctx, query, nodes,
			func(n *AdministrativeArea) { n.Edges.Localities = []*Locality{} },
			func(n *AdministrativeArea, e *Locality) { n.Edges.Localities = append(n.Edges.Localities, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AdministrativeAreaQuery) loadChildren(ctx context.Context, query *AdministrativeAreaQuery, nodes []*AdministrativeArea, init func(*AdministrativeArea), assign func(*AdministrativeArea, *AdministrativeArea)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*AdministrativeArea)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(administrativearea.FieldParentID)
	}
	query.Where(predicate.AdministrativeArea(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(administrativearea.ChildrenColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ParentID
		if fk == nil {
			return fmt.Errorf(`foreign-key "parent_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "parent_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AdministrativeAreaQuery) loadParent(ctx context.Context, query *AdministrativeAreaQuery, nodes []*AdministrativeArea, init func(*AdministrativeArea), assign func(*AdministrativeArea, *AdministrativeArea)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AdministrativeArea)
	for i := range nodes {
		if nodes[i].ParentID == nil {
			continue
		}
		fk := *nodes[i].ParentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(administrativearea.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "parent_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AdministrativeAreaQuery) loadLocalities(ctx context.Context, query *LocalityQuery, nodes []*AdministrativeArea, init func(*AdministrativeArea), assign func(*AdministrativeArea, *Locality)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*AdministrativeArea)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(locality.FieldParentParishID)
	}
	query.Where(predicate.Locality(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(administrativearea.LocalitiesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ParentParishID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "parent_parish_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *AdministrativeAreaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AdministrativeAreaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(administrativearea.Table, administrativearea.Columns, sqlgraph.NewFieldSpec(administrativearea.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, administrativearea.FieldID)
		for i := range fields {
			if fields[i] != administrativearea.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withParent != nil {
			_spec.Node.AddColumnOnce(administrativearea.FieldParentID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AdministrativeAreaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(administrativearea.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = administrativearea.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AdministrativeAreaGroupBy is the group-by builder for AdministrativeArea entities.
type AdministrativeAreaGroupBy struct {
	selector
	build *AdministrativeAreaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AdministrativeAreaGroupBy) Aggregate(fns ...AggregateFunc) *AdministrativeAreaGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AdministrativeAreaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdministrativeAreaQuery, *AdministrativeAreaGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AdministrativeAreaGroupBy) sqlScan(ctx context.Context, root *AdministrativeAreaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AdministrativeAreaSelect is the builder for selecting fields of AdministrativeArea entities.
type AdministrativeAreaSelect struct {
	*AdministrativeAreaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AdministrativeAreaSelect) Aggregate(fns ...AggregateFunc) *AdministrativeAreaSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AdministrativeAreaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdministrativeAreaQuery, *AdministrativeAreaSelect](ctx, _s.AdministrativeAreaQuery, _s, _s.inters, v)
}

func (_s *AdministrativeAreaSelect) sqlScan(ctx context.Context, root *AdministrativeAreaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
