// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/contactrevealdailylimit"
	"github.com/google/uuid"
)

// ContactRevealDailyLimit is the model entity for the ContactRevealDailyLimit schema.
type ContactRevealDailyLimit struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CustomerInternalUserID holds the value of the "customer_internal_user_id" field.
	CustomerInternalUserID uuid.UUID `json:"customer_internal_user_id,omitempty"`
	// UtcDay holds the value of the "utc_day" field.
	UtcDay time.Time `json:"utc_day,omitempty"`
	// SuccessfulCount holds the value of the "successful_count" field.
	SuccessfulCount int `json:"successful_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContactRevealDailyLimit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contactrevealdailylimit.FieldSuccessfulCount:
			values[i] = new(sql.NullInt64)
		case contactrevealdailylimit.FieldUtcDay, contactrevealdailylimit.FieldCreatedAt, contactrevealdailylimit.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case contactrevealdailylimit.FieldID, contactrevealdailylimit.FieldCustomerInternalUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContactRevealDailyLimit fields.
func (_m *ContactRevealDailyLimit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contactrevealdailylimit.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case contactrevealdailylimit.FieldCustomerInternalUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field customer_internal_user_id", values[i])
			} else if value != nil {
				_m.CustomerInternalUserID = *value
			}
		case contactrevealdailylimit.FieldUtcDay:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field utc_day", values[i])
			} else if value.Valid {
				_m.UtcDay = value.Time
			}
		case contactrevealdailylimit.FieldSuccessfulCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field successful_count", values[i])
			} else if value.Valid {
				_m.SuccessfulCount = int(value.Int64)
			}
		case contactrevealdailylimit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case contactrevealdailylimit.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContactRevealDailyLimit.
// This includes values selected through modifiers, order, etc.
func (_m *ContactRevealDailyLimit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ContactRevealDailyLimit.
// Note that you need to call ContactRevealDailyLimit.Unwrap() before calling this method if this ContactRevealDailyLimit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ContactRevealDailyLimit) Update() *ContactRevealDailyLimitUpdateOne {
	return NewContactRevealDailyLimitClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ContactRevealDailyLimit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ContactRevealDailyLimit) Unwrap() *ContactRevealDailyLimit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContactRevealDailyLimit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ContactRevealDailyLimit) String() string {
	var builder strings.Builder
	builder.WriteString("ContactRevealDailyLimit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("customer_internal_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CustomerInternalUserID))
	builder.WriteString(", ")
	builder.WriteString("utc_day=")
	builder.WriteString(_m.UtcDay.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("successful_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuccessfulCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ContactRevealDailyLimits is a parsable slice of ContactRevealDailyLimit.
type ContactRevealDailyLimits []*ContactRevealDailyLimit
