// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/contactrevealevent"
	"github.com/google/uuid"
)

// ContactRevealEventCreate is the builder for creating a ContactRevealEvent entity.
type ContactRevealEventCreate struct {
	config
	mutation *ContactRevealEventMutation
	hooks    []Hook
}

// SetCustomerInternalUserID sets the "customer_internal_user_id" field.
func (_c *ContactRevealEventCreate) SetCustomerInternalUserID(v uuid.UUID) *ContactRevealEventCreate {
	_c.mutation.SetCustomerInternalUserID(v)
	return _c
}

// SetProviderInternalUserID sets the "provider_internal_user_id" field.
func (_c *ContactRevealEventCreate) SetProviderInternalUserID(v uuid.UUID) *ContactRevealEventCreate {
	_c.mutation.SetProviderInternalUserID(v)
	return _c
}

// SetListingID sets the "listing_id" field.
func (_c *ContactRevealEventCreate) SetListingID(v uuid.UUID) *ContactRevealEventCreate {
	_c.mutation.SetListingID(v)
	return _c
}

// SetChannel sets the "channel" field.
func (_c *ContactRevealEventCreate) SetChannel(v contactrevealevent.Channel) *ContactRevealEventCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetUtcDay sets the "utc_day" field.
func (_c *ContactRevealEventCreate) SetUtcDay(v time.Time) *ContactRevealEventCreate {
	_c.mutation.SetUtcDay(v)
	return _c
}

// SetRevealedAt sets the "revealed_at" field.
func (_c *ContactRevealEventCreate) SetRevealedAt(v time.Time) *ContactRevealEventCreate {
	_c.mutation.SetRevealedAt(v)
	return _c
}

// SetNillableRevealedAt sets the "revealed_at" field if the given value is not nil.
func (_c *ContactRevealEventCreate) SetNillableRevealedAt(v *time.Time) *ContactRevealEventCreate {
	if v != nil {
		_c.SetRevealedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ContactRevealEventCreate) SetID(v uuid.UUID) *ContactRevealEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ContactRevealEventCreate) SetNillableID(v *uuid.UUID) *ContactRevealEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ContactRevealEventMutation object of the builder.
func (_c *ContactRevealEventCreate) Mutation() *ContactRevealEventMutation {
	return _c.mutation
}

// Save creates the ContactRevealEvent in the database.
func (_c *ContactRevealEventCreate) Save(ctx context.Context) (*ContactRevealEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContactRevealEventCreate) SaveX(ctx context.Context) *ContactRevealEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContactRevealEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContactRevealEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContactRevealEventCreate) defaults() {
	if _, ok := _c.mutation.RevealedAt(); !ok {
		v := contactrevealevent.DefaultRevealedAt()
		_c.mutation.SetRevealedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := contactrevealevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContactRevealEventCreate) check() error {
	if _, ok := _c.mutation.CustomerInternalUserID(); !ok {
		return &ValidationError{Name: "customer_internal_user_id", err: errors.New(`ent: missing required field "ContactRevealEvent.customer_internal_user_id"`)}
	}
	if _, ok := _c.mutation.ProviderInternalUserID(); !ok {
		return &ValidationError{Name: "provider_internal_user_id", err: errors.New(`ent: missing required field "ContactRevealEvent.provider_internal_user_id"`)}
	}
	if _, ok := _c.mutation.ListingID(); !ok {
		return &ValidationError{Name: "listing_id", err: errors.New(`ent: missing required field "ContactRevealEvent.listing_id"`)}
	}
	if _, ok := _c.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required field "ContactRevealEvent.channel"`)}
	}
	if v, ok := _c.mutation.Channel(); ok {
		if err := contactrevealevent.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "ContactRevealEvent.channel": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UtcDay(); !ok {
		return &ValidationError{Name: "utc_day", err: errors.New(`ent: missing required field "ContactRevealEvent.utc_day"`)}
	}
	if _, ok := _c.mutation.RevealedAt(); !ok {
		return &ValidationError{Name: "revealed_at", err: errors.New(`ent: missing required field "ContactRevealEvent.revealed_at"`)}
	}
	return nil
}

func (_c *ContactRevealEventCreate) sqlSave(ctx context.Context) (*ContactRevealEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContactRevealEventCreate) createSpec() (*ContactRevealEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &ContactRevealEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contactrevealevent.Table, sqlgraph.NewFieldSpec(contactrevealevent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CustomerInternalUserID(); ok {
		_spec.SetField(contactrevealevent.FieldCustomerInternalUserID, field.TypeUUID, value)
		_node.CustomerInternalUserID = value
	}
	if value, ok := _c.mutation.ProviderInternalUserID(); ok {
		_spec.SetField(contactrevealevent.FieldProviderInternalUserID, field.TypeUUID, value)
		_node.ProviderInternalUserID = value
	}
	if value, ok := _c.mutation.ListingID(); ok {
		_spec.SetField(contactrevealevent.FieldListingID, field.TypeUUID, value)
		_node.ListingID = value
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(contactrevealevent.FieldChannel, field.TypeEnum, value)
		_node.Channel = value
	}
	if value, ok := _c.mutation.UtcDay(); ok {
		_spec.SetField(contactrevealevent.FieldUtcDay, field.TypeTime, value)
		_node.UtcDay = value
	}
	if value, ok := _c.mutation.RevealedAt(); ok {
		_spec.SetField(contactrevealevent.FieldRevealedAt, field.TypeTime, value)
		_node.RevealedAt = value
	}
	return _node, _spec
}

// ContactRevealEventCreateBulk is the builder for creating many ContactRevealEvent entities in bulk.
type ContactRevealEventCreateBulk struct {
	config
	err      error
	builders []*ContactRevealEventCreate
}

// Save creates the ContactRevealEvent entities in the database.
func (_c *ContactRevealEventCreateBulk) Save(ctx context.Context) ([]*ContactRevealEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContactRevealEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContactRevealEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContactRevealEventCreateBulk) SaveX(ctx context.Context) []*ContactRevealEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContactRevealEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContactRevealEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
