// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/contactrevealdailylimit"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/predicate"
)

// ContactRevealDailyLimitDelete is the builder for deleting a ContactRevealDailyLimit entity.
type ContactRevealDailyLimitDelete struct {
	config
	hooks    []Hook
	mutation *ContactRevealDailyLimitMutation
}

// Where appends a list predicates to the ContactRevealDailyLimitDelete builder.
func (_d *ContactRevealDailyLimitDelete) Where(ps ...predicate.ContactRevealDailyLimit) *ContactRevealDailyLimitDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ContactRevealDailyLimitDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ContactRevealDailyLimitDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ContactRevealDailyLimitDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(contactrevealdailylimit.Table, sqlgraph.NewFieldSpec(contactrevealdailylimit.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ContactRevealDailyLimitDeleteOne is the builder for deleting a single ContactRevealDailyLimit entity.
type ContactRevealDailyLimitDeleteOne struct {
	_d *ContactRevealDailyLimitDelete
}

// Where appends a list predicates to the ContactRevealDailyLimitDelete builder.
func (_d *ContactRevealDailyLimitDeleteOne) Where(ps ...predicate.ContactRevealDailyLimit) *ContactRevealDailyLimitDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ContactRevealDailyLimitDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{contactrevealdailylimit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ContactRevealDailyLimitDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
