// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/internaluser"
	"github.com/google/uuid"
)

// InternalUserCreate is the builder for creating a InternalUser entity.
type InternalUserCreate struct {
	config
	mutation *InternalUserMutation
	hooks    []Hook
}

// SetClerkSubject sets the "clerk_subject" field.
func (_c *InternalUserCreate) SetClerkSubject(v string) *InternalUserCreate {
	_c.mutation.SetClerkSubject(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InternalUserCreate) SetCreatedAt(v time.Time) *InternalUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InternalUserCreate) SetNillableCreatedAt(v *time.Time) *InternalUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InternalUserCreate) SetUpdatedAt(v time.Time) *InternalUserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InternalUserCreate) SetNillableUpdatedAt(v *time.Time) *InternalUserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InternalUserCreate) SetID(v uuid.UUID) *InternalUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *InternalUserCreate) SetNillableID(v *uuid.UUID) *InternalUserCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the InternalUserMutation object of the builder.
func (_c *InternalUserCreate) Mutation() *InternalUserMutation {
	return _c.mutation
}

// Save creates the InternalUser in the database.
func (_c *InternalUserCreate) Save(ctx context.Context) (*InternalUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InternalUserCreate) SaveX(ctx context.Context) *InternalUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InternalUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InternalUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InternalUserCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := internaluser.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := internaluser.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := internaluser.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InternalUserCreate) check() error {
	if _, ok := _c.mutation.ClerkSubject(); !ok {
		return &ValidationError{Name: "clerk_subject", err: errors.New(`ent: missing required field "InternalUser.clerk_subject"`)}
	}
	if v, ok := _c.mutation.ClerkSubject(); ok {
		if err := internaluser.ClerkSubjectValidator(v); err != nil {
			return &ValidationError{Name: "clerk_subject", err: fmt.Errorf(`ent: validator failed for field "InternalUser.clerk_subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InternalUser.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InternalUser.updated_at"`)}
	}
	return nil
}

func (_c *InternalUserCreate) sqlSave(ctx context.Context) (*InternalUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InternalUserCreate) createSpec() (*InternalUser, *sqlgraph.CreateSpec) {
	var (
		_node = &InternalUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(internaluser.Table, sqlgraph.NewFieldSpec(internaluser.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ClerkSubject(); ok {
		_spec.SetField(internaluser.FieldClerkSubject, field.TypeString, value)
		_node.ClerkSubject = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(internaluser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(internaluser.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// InternalUserCreateBulk is the builder for creating many InternalUser entities in bulk.
type InternalUserCreateBulk struct {
	config
	err      error
	builders []*InternalUserCreate
}

// Save creates the InternalUser entities in the database.
func (_c *InternalUserCreateBulk) Save(ctx context.Context) ([]*InternalUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InternalUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InternalUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InternalUserCreateBulk) SaveX(ctx context.Context) []*InternalUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InternalUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InternalUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
