// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/listing"
	"github.com/google/uuid"
)

// Listing is the model entity for the Listing schema.
type Listing struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// InternalUserID holds the value of the "internal_user_id" field.
	InternalUserID uuid.UUID `json:"internal_user_id,omitempty"`
	// CategoryID holds the value of the "category_id" field.
	CategoryID uuid.UUID `json:"category_id,omitempty"`
	// PrimaryLocalityID holds the value of the "primary_locality_id" field.
	PrimaryLocalityID uuid.UUID `json:"primary_locality_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// PriceType holds the value of the "price_type" field.
	PriceType listing.PriceType `json:"price_type,omitempty"`
	// PriceMinor holds the value of the "price_minor" field.
	PriceMinor *int `json:"price_minor,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// TravelsToCustomer holds the value of the "travels_to_customer" field.
	TravelsToCustomer bool `json:"travels_to_customer,omitempty"`
	// ReceivesCustomer holds the value of the "receives_customer" field.
	ReceivesCustomer bool `json:"receives_customer,omitempty"`
	// RemoteServices holds the value of the "remote_services" field.
	RemoteServices bool `json:"remote_services,omitempty"`
	// State holds the value of the "state" field.
	State listing.State `json:"state,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision int `json:"revision,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Listing) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case listing.FieldTravelsToCustomer, listing.FieldReceivesCustomer, listing.FieldRemoteServices:
			values[i] = new(sql.NullBool)
		case listing.FieldPriceMinor, listing.FieldRevision:
			values[i] = new(sql.NullInt64)
		case listing.FieldTitle, listing.FieldDescription, listing.FieldPriceType, listing.FieldCurrency, listing.FieldState:
			values[i] = new(sql.NullString)
		case listing.FieldCreatedAt, listing.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case listing.FieldID, listing.FieldInternalUserID, listing.FieldCategoryID, listing.FieldPrimaryLocalityID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Listing fields.
func (_m *Listing) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case listing.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case listing.FieldInternalUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field internal_user_id", values[i])
			} else if value != nil {
				_m.InternalUserID = *value
			}
		case listing.FieldCategoryID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field category_id", values[i])
			} else if value != nil {
				_m.CategoryID = *value
			}
		case listing.FieldPrimaryLocalityID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field primary_locality_id", values[i])
			} else if value != nil {
				_m.PrimaryLocalityID = *value
			}
		case listing.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case listing.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case listing.FieldPriceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field price_type", values[i])
			} else if value.Valid {
				_m.PriceType = listing.PriceType(value.String)
			}
		case listing.FieldPriceMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_minor", values[i])
			} else if value.Valid {
				_m.PriceMinor = new(int)
				*_m.PriceMinor = int(value.Int64)
			}
		case listing.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case listing.FieldTravelsToCustomer:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field travels_to_customer", values[i])
			} else if value.Valid {
				_m.TravelsToCustomer = value.Bool
			}
		case listing.FieldReceivesCustomer:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field receives_customer", values[i])
			} else if value.Valid {
				_m.ReceivesCustomer = value.Bool
			}
		case listing.FieldRemoteServices:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field remote_services", values[i])
			} else if value.Valid {
				_m.RemoteServices = value.Bool
			}
		case listing.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = listing.State(value.String)
			}
		case listing.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = int(value.Int64)
			}
		case listing.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case listing.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Listing.
// This includes values selected through modifiers, order, etc.
func (_m *Listing) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Listing.
// Note that you need to call Listing.Unwrap() before calling this method if this Listing
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Listing) Update() *ListingUpdateOne {
	return NewListingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Listing entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Listing) Unwrap() *Listing {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Listing is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Listing) String() string {
	var builder strings.Builder
	builder.WriteString("Listing(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("internal_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InternalUserID))
	builder.WriteString(", ")
	builder.WriteString("category_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CategoryID))
	builder.WriteString(", ")
	builder.WriteString("primary_locality_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrimaryLocalityID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("price_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceType))
	builder.WriteString(", ")
	if v := _m.PriceMinor; v != nil {
		builder.WriteString("price_minor=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("travels_to_customer=")
	builder.WriteString(fmt.Sprintf("%v", _m.TravelsToCustomer))
	builder.WriteString(", ")
	builder.WriteString("receives_customer=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReceivesCustomer))
	builder.WriteString(", ")
	builder.WriteString("remote_services=")
	builder.WriteString(fmt.Sprintf("%v", _m.RemoteServices))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Listings is a parsable slice of Listing.
type Listings []*Listing
