// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/listingevent"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/predicate"
)

// ListingEventUpdate is the builder for updating ListingEvent entities.
type ListingEventUpdate struct {
	config
	hooks    []Hook
	mutation *ListingEventMutation
}

// Where appends a list predicates to the ListingEventUpdate builder.
func (_u *ListingEventUpdate) Where(ps ...predicate.ListingEvent) *ListingEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the ListingEventMutation object of the builder.
func (_u *ListingEventUpdate) Mutation() *ListingEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ListingEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ListingEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ListingEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ListingEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ListingEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(listingevent.Table, listingevent.Columns, sqlgraph.NewFieldSpec(listingevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.FromStateCleared() {
		_spec.ClearField(listingevent.FieldFromState, field.TypeString)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(listingevent.FieldReason, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{listingevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ListingEventUpdateOne is the builder for updating a single ListingEvent entity.
type ListingEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ListingEventMutation
}

// Mutation returns the ListingEventMutation object of the builder.
func (_u *ListingEventUpdateOne) Mutation() *ListingEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the ListingEventUpdate builder.
func (_u *ListingEventUpdateOne) Where(ps ...predicate.ListingEvent) *ListingEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ListingEventUpdateOne) Select(field string, fields ...string) *ListingEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ListingEvent entity.
func (_u *ListingEventUpdateOne) Save(ctx context.Context) (*ListingEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ListingEventUpdateOne) SaveX(ctx context.Context) *ListingEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ListingEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ListingEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ListingEventUpdateOne) sqlSave(ctx context.Context) (_node *ListingEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(listingevent.Table, listingevent.Columns, sqlgraph.NewFieldSpec(listingevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ListingEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, listingevent.FieldID)
		for _, f := range fields {
			if !listingevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != listingevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.FromStateCleared() {
		_spec.ClearField(listingevent.FieldFromState, field.TypeString)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(listingevent.FieldReason, field.TypeString)
	}
	_node = &ListingEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{listingevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
