// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/listingmedia"
	"github.com/google/uuid"
)

// ListingMediaCreate is the builder for creating a ListingMedia entity.
type ListingMediaCreate struct {
	config
	mutation *ListingMediaMutation
	hooks    []Hook
}

// SetListingID sets the "listing_id" field.
func (_c *ListingMediaCreate) SetListingID(v uuid.UUID) *ListingMediaCreate {
	_c.mutation.SetListingID(v)
	return _c
}

// SetOrdinal sets the "ordinal" field.
func (_c *ListingMediaCreate) SetOrdinal(v int) *ListingMediaCreate {
	_c.mutation.SetOrdinal(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *ListingMediaCreate) SetContentType(v string) *ListingMediaCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetByteSize sets the "byte_size" field.
func (_c *ListingMediaCreate) SetByteSize(v int64) *ListingMediaCreate {
	_c.mutation.SetByteSize(v)
	return _c
}

// SetChecksumSha256 sets the "checksum_sha256" field.
func (_c *ListingMediaCreate) SetChecksumSha256(v string) *ListingMediaCreate {
	_c.mutation.SetChecksumSha256(v)
	return _c
}

// SetObjectReference sets the "object_reference" field.
func (_c *ListingMediaCreate) SetObjectReference(v string) *ListingMediaCreate {
	_c.mutation.SetObjectReference(v)
	return _c
}

// SetState sets the "state" field.
func (_c *ListingMediaCreate) SetState(v listingmedia.State) *ListingMediaCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *ListingMediaCreate) SetNillableState(v *listingmedia.State) *ListingMediaCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ListingMediaCreate) SetCreatedAt(v time.Time) *ListingMediaCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ListingMediaCreate) SetNillableCreatedAt(v *time.Time) *ListingMediaCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ListingMediaCreate) SetUpdatedAt(v time.Time) *ListingMediaCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ListingMediaCreate) SetNillableUpdatedAt(v *time.Time) *ListingMediaCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ListingMediaCreate) SetID(v uuid.UUID) *ListingMediaCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ListingMediaCreate) SetNillableID(v *uuid.UUID) *ListingMediaCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ListingMediaMutation object of the builder.
func (_c *ListingMediaCreate) Mutation() *ListingMediaMutation {
	return _c.mutation
}

// Save creates the ListingMedia in the database.
func (_c *ListingMediaCreate) Save(ctx context.Context) (*ListingMedia, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ListingMediaCreate) SaveX(ctx context.Context) *ListingMedia {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListingMediaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListingMediaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ListingMediaCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := listingmedia.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := listingmedia.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := listingmedia.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := listingmedia.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ListingMediaCreate) check() error {
	if _, ok := _c.mutation.ListingID(); !ok {
		return &ValidationError{Name: "listing_id", err: errors.New(`ent: missing required field "ListingMedia.listing_id"`)}
	}
	if _, ok := _c.mutation.Ordinal(); !ok {
		return &ValidationError{Name: "ordinal", err: errors.New(`ent: missing required field "ListingMedia.ordinal"`)}
	}
	if v, ok := _c.mutation.Ordinal(); ok {
		if err := listingmedia.OrdinalValidator(v); err != nil {
			return &ValidationError{Name: "ordinal", err: fmt.Errorf(`ent: validator failed for field "ListingMedia.ordinal": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "ListingMedia.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := listingmedia.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "ListingMedia.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ByteSize(); !ok {
		return &ValidationError{Name: "byte_size", err: errors.New(`ent: missing required field "ListingMedia.byte_size"`)}
	}
	if v, ok := _c.mutation.ByteSize(); ok {
		if err := listingmedia.ByteSizeValidator(v); err != nil {
			return &ValidationError{Name: "byte_size", err: fmt.Errorf(`ent: validator failed for field "ListingMedia.byte_size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChecksumSha256(); !ok {
		return &ValidationError{Name: "checksum_sha256", err: errors.New(`ent: missing required field "ListingMedia.checksum_sha256"`)}
	}
	if v, ok := _c.mutation.ChecksumSha256(); ok {
		if err := listingmedia.ChecksumSha256Validator(v); err != nil {
			return &ValidationError{Name: "checksum_sha256", err: fmt.Errorf(`ent: validator failed for field "ListingMedia.checksum_sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ObjectReference(); !ok {
		return &ValidationError{Name: "object_reference", err: errors.New(`ent: missing required field "ListingMedia.object_reference"`)}
	}
	if v, ok := _c.mutation.ObjectReference(); ok {
		if err := listingmedia.ObjectReferenceValidator(v); err != nil {
			return &ValidationError{Name: "object_reference", err: fmt.Errorf(`ent: validator failed for field "ListingMedia.object_reference": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "ListingMedia.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := listingmedia.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "ListingMedia.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ListingMedia.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ListingMedia.updated_at"`)}
	}
	return nil
}

func (_c *ListingMediaCreate) sqlSave(ctx context.Context) (*ListingMedia, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ListingMediaCreate) createSpec() (*ListingMedia, *sqlgraph.CreateSpec) {
	var (
		_node = &ListingMedia{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(listingmedia.Table, sqlgraph.NewFieldSpec(listingmedia.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ListingID(); ok {
		_spec.SetField(listingmedia.FieldListingID, field.TypeUUID, value)
		_node.ListingID = value
	}
	if value, ok := _c.mutation.Ordinal(); ok {
		_spec.SetField(listingmedia.FieldOrdinal, field.TypeInt, value)
		_node.Ordinal = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(listingmedia.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.ByteSize(); ok {
		_spec.SetField(listingmedia.FieldByteSize, field.TypeInt64, value)
		_node.ByteSize = value
	}
	if value, ok := _c.mutation.ChecksumSha256(); ok {
		_spec.SetField(listingmedia.FieldChecksumSha256, field.TypeString, value)
		_node.ChecksumSha256 = value
	}
	if value, ok := _c.mutation.ObjectReference(); ok {
		_spec.SetField(listingmedia.FieldObjectReference, field.TypeString, value)
		_node.ObjectReference = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(listingmedia.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(listingmedia.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(listingmedia.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ListingMediaCreateBulk is the builder for creating many ListingMedia entities in bulk.
type ListingMediaCreateBulk struct {
	config
	err      error
	builders []*ListingMediaCreate
}

// Save creates the ListingMedia entities in the database.
func (_c *ListingMediaCreateBulk) Save(ctx context.Context) ([]*ListingMedia, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ListingMedia, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ListingMediaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ListingMediaCreateBulk) SaveX(ctx context.Context) []*ListingMedia {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListingMediaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListingMediaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
