// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/platformrole"
	"github.com/google/uuid"
)

// PlatformRole is the model entity for the PlatformRole schema.
type PlatformRole struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// InternalUserID holds the value of the "internal_user_id" field.
	InternalUserID uuid.UUID `json:"internal_user_id,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// GrantedAt holds the value of the "granted_at" field.
	GrantedAt    time.Time `json:"granted_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlatformRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case platformrole.FieldRole:
			values[i] = new(sql.NullString)
		case platformrole.FieldGrantedAt:
			values[i] = new(sql.NullTime)
		case platformrole.FieldID, platformrole.FieldInternalUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlatformRole fields.
func (_m *PlatformRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case platformrole.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case platformrole.FieldInternalUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field internal_user_id", values[i])
			} else if value != nil {
				_m.InternalUserID = *value
			}
		case platformrole.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case platformrole.FieldGrantedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field granted_at", values[i])
			} else if value.Valid {
				_m.GrantedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlatformRole.
// This includes values selected through modifiers, order, etc.
func (_m *PlatformRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PlatformRole.
// Note that you need to call PlatformRole.Unwrap() before calling this method if this PlatformRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlatformRole) Update() *PlatformRoleUpdateOne {
	return NewPlatformRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlatformRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlatformRole) Unwrap() *PlatformRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlatformRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlatformRole) String() string {
	var builder strings.Builder
	builder.WriteString("PlatformRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("internal_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InternalUserID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("granted_at=")
	builder.WriteString(_m.GrantedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PlatformRoles is a parsable slice of PlatformRole.
type PlatformRoles []*PlatformRole
