// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/providerprofile"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/providerspokenlanguage"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/spokenlanguage"
	"github.com/google/uuid"
)

// ProviderSpokenLanguage is the model entity for the ProviderSpokenLanguage schema.
type ProviderSpokenLanguage struct {
	config `json:"-"`
	// InternalUserID holds the value of the "internal_user_id" field.
	InternalUserID uuid.UUID `json:"internal_user_id,omitempty"`
	// LanguageCode holds the value of the "language_code" field.
	LanguageCode string `json:"language_code,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProviderSpokenLanguageQuery when eager-loading is set.
	Edges        ProviderSpokenLanguageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProviderSpokenLanguageEdges holds the relations/edges for other nodes in the graph.
type ProviderSpokenLanguageEdges struct {
	// Profile holds the value of the profile edge.
	Profile *ProviderProfile `json:"profile,omitempty"`
	// Language holds the value of the language edge.
	Language *SpokenLanguage `json:"language,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProfileOrErr returns the Profile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProviderSpokenLanguageEdges) ProfileOrErr() (*ProviderProfile, error) {
	if e.Profile != nil {
		return e.Profile, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: providerprofile.Label}
	}
	return nil, &NotLoadedError{edge: "profile"}
}

// LanguageOrErr returns the Language value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProviderSpokenLanguageEdges) LanguageOrErr() (*SpokenLanguage, error) {
	if e.Language != nil {
		return e.Language, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: spokenlanguage.Label}
	}
	return nil, &NotLoadedError{edge: "language"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderSpokenLanguage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providerspokenlanguage.FieldLanguageCode:
			values[i] = new(sql.NullString)
		case providerspokenlanguage.FieldInternalUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderSpokenLanguage fields.
func (_m *ProviderSpokenLanguage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providerspokenlanguage.FieldInternalUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field internal_user_id", values[i])
			} else if value != nil {
				_m.InternalUserID = *value
			}
		case providerspokenlanguage.FieldLanguageCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language_code", values[i])
			} else if value.Valid {
				_m.LanguageCode = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderSpokenLanguage.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderSpokenLanguage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProfile queries the "profile" edge of the ProviderSpokenLanguage entity.
func (_m *ProviderSpokenLanguage) QueryProfile() *ProviderProfileQuery {
	return NewProviderSpokenLanguageClient(_m.config).QueryProfile(_m)
}

// QueryLanguage queries the "language" edge of the ProviderSpokenLanguage entity.
func (_m *ProviderSpokenLanguage) QueryLanguage() *SpokenLanguageQuery {
	return NewProviderSpokenLanguageClient(_m.config).QueryLanguage(_m)
}

// Update returns a builder for updating this ProviderSpokenLanguage.
// Note that you need to call ProviderSpokenLanguage.Unwrap() before calling this method if this ProviderSpokenLanguage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderSpokenLanguage) Update() *ProviderSpokenLanguageUpdateOne {
	return NewProviderSpokenLanguageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderSpokenLanguage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderSpokenLanguage) Unwrap() *ProviderSpokenLanguage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderSpokenLanguage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderSpokenLanguage) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderSpokenLanguage(")
	builder.WriteString("internal_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InternalUserID))
	builder.WriteString(", ")
	builder.WriteString("language_code=")
	builder.WriteString(_m.LanguageCode)
	builder.WriteByte(')')
	return builder.String()
}

// ProviderSpokenLanguages is a parsable slice of ProviderSpokenLanguage.
type ProviderSpokenLanguages []*ProviderSpokenLanguage
