// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/locality"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/predicate"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/providerprofile"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/spokenlanguage"
	"github.com/google/uuid"
)

// ProviderProfileUpdate is the builder for updating ProviderProfile entities.
type ProviderProfileUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderProfileMutation
}

// Where appends a list predicates to the ProviderProfileUpdate builder.
func (_u *ProviderProfileUpdate) Where(ps ...predicate.ProviderProfile) *ProviderProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ProviderProfileUpdate) SetDisplayName(v string) *ProviderProfileUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ProviderProfileUpdate) SetNillableDisplayName(v *string) *ProviderProfileUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *ProviderProfileUpdate) SetProviderType(v string) *ProviderProfileUpdate {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *ProviderProfileUpdate) SetNillableProviderType(v *string) *ProviderProfileUpdate {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetBio sets the "bio" field.
func (_u *ProviderProfileUpdate) SetBio(v string) *ProviderProfileUpdate {
	_u.mutation.SetBio(v)
	return _u
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_u *ProviderProfileUpdate) SetNillableBio(v *string) *ProviderProfileUpdate {
	if v != nil {
		_u.SetBio(*v)
	}
	return _u
}

// SetPrimaryLocalityID sets the "primary_locality_id" field.
func (_u *ProviderProfileUpdate) SetPrimaryLocalityID(v uuid.UUID) *ProviderProfileUpdate {
	_u.mutation.SetPrimaryLocalityID(v)
	return _u
}

// SetNillablePrimaryLocalityID sets the "primary_locality_id" field if the given value is not nil.
func (_u *ProviderProfileUpdate) SetNillablePrimaryLocalityID(v *uuid.UUID) *ProviderProfileUpdate {
	if v != nil {
		_u.SetPrimaryLocalityID(*v)
	}
	return _u
}

// SetMaxTravelDistanceKm sets the "max_travel_distance_km" field.
func (_u *ProviderProfileUpdate) SetMaxTravelDistanceKm(v int) *ProviderProfileUpdate {
	_u.mutation.ResetMaxTravelDistanceKm()
	_u.mutation.SetMaxTravelDistanceKm(v)
	return _u
}

// SetNillableMaxTravelDistanceKm sets the "max_travel_distance_km" field if the given value is not nil.
func (_u *ProviderProfileUpdate) SetNillableMaxTravelDistanceKm(v *int) *ProviderProfileUpdate {
	if v != nil {
		_u.SetMaxTravelDistanceKm(*v)
	}
	return _u
}

// AddMaxTravelDistanceKm adds value to the "max_travel_distance_km" field.
func (_u *ProviderProfileUpdate) AddMaxTravelDistanceKm(v int) *ProviderProfileUpdate {
	_u.mutation.AddMaxTravelDistanceKm(v)
	return _u
}

// SetTravelsToCustomer sets the "travels_to_customer" field.
func (_u *ProviderProfileUpdate) SetTravelsToCustomer(v bool) *ProviderProfileUpdate {
	_u.mutation.SetTravelsToCustomer(v)
	return _u
}

// SetNillableTravelsToCustomer sets the "travels_to_customer" field if the given value is not nil.
func (_u *ProviderProfileUpdate) SetNillableTravelsToCustomer(v *bool) *ProviderProfileUpdate {
	if v != nil {
		_u.SetTravelsToCustomer(*v)
	}
	return _u
}

// SetReceivesCustomer sets the "receives_customer" field.
func (_u *ProviderProfileUpdate) SetReceivesCustomer(v bool) *ProviderProfileUpdate {
	_u.mutation.SetReceivesCustomer(v)
	return _u
}

// SetNillableReceivesCustomer sets the "receives_customer" field if the given value is not nil.
func (_u *ProviderProfileUpdate) SetNillableReceivesCustomer(v *bool) *ProviderProfileUpdate {
	if v != nil {
		_u.SetReceivesCustomer(*v)
	}
	return _u
}

// SetRemoteServices sets the "remote_services" field.
func (_u *ProviderProfileUpdate) SetRemoteServices(v bool) *ProviderProfileUpdate {
	_u.mutation.SetRemoteServices(v)
	return _u
}

// SetNillableRemoteServices sets the "remote_services" field if the given value is not nil.
func (_u *ProviderProfileUpdate) SetNillableRemoteServices(v *bool) *ProviderProfileUpdate {
	if v != nil {
		_u.SetRemoteServices(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderProfileUpdate) SetUpdatedAt(v time.Time) *ProviderProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddServiceLocalityIDs adds the "service_localities" edge to the Locality entity by IDs.
func (_u *ProviderProfileUpdate) AddServiceLocalityIDs(ids ...uuid.UUID) *ProviderProfileUpdate {
	_u.mutation.AddServiceLocalityIDs(ids...)
	return _u
}

// AddServiceLocalities adds the "service_localities" edges to the Locality entity.
func (_u *ProviderProfileUpdate) AddServiceLocalities(v ...*Locality) *ProviderProfileUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddServiceLocalityIDs(ids...)
}

// AddSpokenLanguageIDs adds the "spoken_languages" edge to the SpokenLanguage entity by IDs.
func (_u *ProviderProfileUpdate) AddSpokenLanguageIDs(ids ...string) *ProviderProfileUpdate {
	_u.mutation.AddSpokenLanguageIDs(ids...)
	return _u
}

// AddSpokenLanguages adds the "spoken_languages" edges to the SpokenLanguage entity.
func (_u *ProviderProfileUpdate) AddSpokenLanguages(v ...*SpokenLanguage) *ProviderProfileUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSpokenLanguageIDs(ids...)
}

// Mutation returns the ProviderProfileMutation object of the builder.
func (_u *ProviderProfileUpdate) Mutation() *ProviderProfileMutation {
	return _u.mutation
}

// ClearServiceLocalities clears all "service_localities" edges to the Locality entity.
func (_u *ProviderProfileUpdate) ClearServiceLocalities() *ProviderProfileUpdate {
	_u.mutation.ClearServiceLocalities()
	return _u
}

// RemoveServiceLocalityIDs removes the "service_localities" edge to Locality entities by IDs.
func (_u *ProviderProfileUpdate) RemoveServiceLocalityIDs(ids ...uuid.UUID) *ProviderProfileUpdate {
	_u.mutation.RemoveServiceLocalityIDs(ids...)
	return _u
}

// RemoveServiceLocalities removes "service_localities" edges to Locality entities.
func (_u *ProviderProfileUpdate) RemoveServiceLocalities(v ...*Locality) *ProviderProfileUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveServiceLocalityIDs(ids...)
}

// ClearSpokenLanguages clears all "spoken_languages" edges to the SpokenLanguage entity.
func (_u *ProviderProfileUpdate) ClearSpokenLanguages() *ProviderProfileUpdate {
	_u.mutation.ClearSpokenLanguages()
	return _u
}

// RemoveSpokenLanguageIDs removes the "spoken_languages" edge to SpokenLanguage entities by IDs.
func (_u *ProviderProfileUpdate) RemoveSpokenLanguageIDs(ids ...string) *ProviderProfileUpdate {
	_u.mutation.RemoveSpokenLanguageIDs(ids...)
	return _u
}

// RemoveSpokenLanguages removes "spoken_languages" edges to SpokenLanguage entities.
func (_u *ProviderProfileUpdate) RemoveSpokenLanguages(v ...*SpokenLanguage) *ProviderProfileUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSpokenLanguageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providerprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderProfileUpdate) check() error {
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := providerprofile.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ProviderProfile.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := providerprofile.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "ProviderProfile.provider_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bio(); ok {
		if err := providerprofile.BioValidator(v); err != nil {
			return &ValidationError{Name: "bio", err: fmt.Errorf(`ent: validator failed for field "ProviderProfile.bio": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxTravelDistanceKm(); ok {
		if err := providerprofile.MaxTravelDistanceKmValidator(v); err != nil {
			return &ValidationError{Name: "max_travel_distance_km", err: fmt.Errorf(`ent: validator failed for field "ProviderProfile.max_travel_distance_km": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerprofile.Table, providerprofile.Columns, sqlgraph.NewFieldSpec(providerprofile.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(providerprofile.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(providerprofile.FieldProviderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bio(); ok {
		_spec.SetField(providerprofile.FieldBio, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrimaryLocalityID(); ok {
		_spec.SetField(providerprofile.FieldPrimaryLocalityID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.MaxTravelDistanceKm(); ok {
		_spec.SetField(providerprofile.FieldMaxTravelDistanceKm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTravelDistanceKm(); ok {
		_spec.AddField(providerprofile.FieldMaxTravelDistanceKm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TravelsToCustomer(); ok {
		_spec.SetField(providerprofile.FieldTravelsToCustomer, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReceivesCustomer(); ok {
		_spec.SetField(providerprofile.FieldReceivesCustomer, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RemoteServices(); ok {
		_spec.SetField(providerprofile.FieldRemoteServices, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providerprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ServiceLocalitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   providerprofile.ServiceLocalitiesTable,
			Columns: providerprofile.ServiceLocalitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locality.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedServiceLocalitiesIDs(); len(nodes) > 0 && !_u.mutation.ServiceLocalitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   providerprofile.ServiceLocalitiesTable,
			Columns: providerprofile.ServiceLocalitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locality.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServiceLocalitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   providerprofile.ServiceLocalitiesTable,
			Columns: providerprofile.ServiceLocalitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locality.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SpokenLanguagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   providerprofile.SpokenLanguagesTable,
			Columns: providerprofile.SpokenLanguagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spokenlanguage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSpokenLanguagesIDs(); len(nodes) > 0 && !_u.mutation.SpokenLanguagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   providerprofile.SpokenLanguagesTable,
			Columns: providerprofile.SpokenLanguagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spokenlanguage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SpokenLanguagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   providerprofile.SpokenLanguagesTable,
			Columns: providerprofile.SpokenLanguagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spokenlanguage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderProfileUpdateOne is the builder for updating a single ProviderProfile entity.
type ProviderProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderProfileMutation
}

// SetDisplayName sets the "display_name" field.
func (_u *ProviderProfileUpdateOne) SetDisplayName(v string) *ProviderProfileUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ProviderProfileUpdateOne) SetNillableDisplayName(v *string) *ProviderProfileUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *ProviderProfileUpdateOne) SetProviderType(v string) *ProviderProfileUpdateOne {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *ProviderProfileUpdateOne) SetNillableProviderType(v *string) *ProviderProfileUpdateOne {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetBio sets the "bio" field.
func (_u *ProviderProfileUpdateOne) SetBio(v string) *ProviderProfileUpdateOne {
	_u.mutation.SetBio(v)
	return _u
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_u *ProviderProfileUpdateOne) SetNillableBio(v *string) *ProviderProfileUpdateOne {
	if v != nil {
		_u.SetBio(*v)
	}
	return _u
}

// SetPrimaryLocalityID sets the "primary_locality_id" field.
func (_u *ProviderProfileUpdateOne) SetPrimaryLocalityID(v uuid.UUID) *ProviderProfileUpdateOne {
	_u.mutation.SetPrimaryLocalityID(v)
	return _u
}

// SetNillablePrimaryLocalityID sets the "primary_locality_id" field if the given value is not nil.
func (_u *ProviderProfileUpdateOne) SetNillablePrimaryLocalityID(v *uuid.UUID) *ProviderProfileUpdateOne {
	if v != nil {
		_u.SetPrimaryLocalityID(*v)
	}
	return _u
}

// SetMaxTravelDistanceKm sets the "max_travel_distance_km" field.
func (_u *ProviderProfileUpdateOne) SetMaxTravelDistanceKm(v int) *ProviderProfileUpdateOne {
	_u.mutation.ResetMaxTravelDistanceKm()
	_u.mutation.SetMaxTravelDistanceKm(v)
	return _u
}

// SetNillableMaxTravelDistanceKm sets the "max_travel_distance_km" field if the given value is not nil.
func (_u *ProviderProfileUpdateOne) SetNillableMaxTravelDistanceKm(v *int) *ProviderProfileUpdateOne {
	if v != nil {
		_u.SetMaxTravelDistanceKm(*v)
	}
	return _u
}

// AddMaxTravelDistanceKm adds value to the "max_travel_distance_km" field.
func (_u *ProviderProfileUpdateOne) AddMaxTravelDistanceKm(v int) *ProviderProfileUpdateOne {
	_u.mutation.AddMaxTravelDistanceKm(v)
	return _u
}

// SetTravelsToCustomer sets the "travels_to_customer" field.
func (_u *ProviderProfileUpdateOne) SetTravelsToCustomer(v bool) *ProviderProfileUpdateOne {
	_u.mutation.SetTravelsToCustomer(v)
	return _u
}

// SetNillableTravelsToCustomer sets the "travels_to_customer" field if the given value is not nil.
func (_u *ProviderProfileUpdateOne) SetNillableTravelsToCustomer(v *bool) *ProviderProfileUpdateOne {
	if v != nil {
		_u.SetTravelsToCustomer(*v)
	}
	return _u
}

// SetReceivesCustomer sets the "receives_customer" field.
func (_u *ProviderProfileUpdateOne) SetReceivesCustomer(v bool) *ProviderProfileUpdateOne {
	_u.mutation.SetReceivesCustomer(v)
	return _u
}

// SetNillableReceivesCustomer sets the "receives_customer" field if the given value is not nil.
func (_u *ProviderProfileUpdateOne) SetNillableReceivesCustomer(v *bool) *ProviderProfileUpdateOne {
	if v != nil {
		_u.SetReceivesCustomer(*v)
	}
	return _u
}

// SetRemoteServices sets the "remote_services" field.
func (_u *ProviderProfileUpdateOne) SetRemoteServices(v bool) *ProviderProfileUpdateOne {
	_u.mutation.SetRemoteServices(v)
	return _u
}

// SetNillableRemoteServices sets the "remote_services" field if the given value is not nil.
func (_u *ProviderProfileUpdateOne) SetNillableRemoteServices(v *bool) *ProviderProfileUpdateOne {
	if v != nil {
		_u.SetRemoteServices(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderProfileUpdateOne) SetUpdatedAt(v time.Time) *ProviderProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddServiceLocalityIDs adds the "service_localities" edge to the Locality entity by IDs.
func (_u *ProviderProfileUpdateOne) AddServiceLocalityIDs(ids ...uuid.UUID) *ProviderProfileUpdateOne {
	_u.mutation.AddServiceLocalityIDs(ids...)
	return _u
}

// AddServiceLocalities adds the "service_localities" edges to the Locality entity.
func (_u *ProviderProfileUpdateOne) AddServiceLocalities(v ...*Locality) *ProviderProfileUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddServiceLocalityIDs(ids...)
}

// AddSpokenLanguageIDs adds the "spoken_languages" edge to the SpokenLanguage entity by IDs.
func (_u *ProviderProfileUpdateOne) AddSpokenLanguageIDs(ids ...string) *ProviderProfileUpdateOne {
	_u.mutation.AddSpokenLanguageIDs(ids...)
	return _u
}

// AddSpokenLanguages adds the "spoken_languages" edges to the SpokenLanguage entity.
func (_u *ProviderProfileUpdateOne) AddSpokenLanguages(v ...*SpokenLanguage) *ProviderProfileUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSpokenLanguageIDs(ids...)
}

// Mutation returns the ProviderProfileMutation object of the builder.
func (_u *ProviderProfileUpdateOne) Mutation() *ProviderProfileMutation {
	return _u.mutation
}

// ClearServiceLocalities clears all "service_localities" edges to the Locality entity.
func (_u *ProviderProfileUpdateOne) ClearServiceLocalities() *ProviderProfileUpdateOne {
	_u.mutation.ClearServiceLocalities()
	return _u
}

// RemoveServiceLocalityIDs removes the "service_localities" edge to Locality entities by IDs.
func (_u *ProviderProfileUpdateOne) RemoveServiceLocalityIDs(ids ...uuid.UUID) *ProviderProfileUpdateOne {
	_u.mutation.RemoveServiceLocalityIDs(ids...)
	return _u
}

// RemoveServiceLocalities removes "service_localities" edges to Locality entities.
func (_u *ProviderProfileUpdateOne) RemoveServiceLocalities(v ...*Locality) *ProviderProfileUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveServiceLocalityIDs(ids...)
}

// ClearSpokenLanguages clears all "spoken_languages" edges to the SpokenLanguage entity.
func (_u *ProviderProfileUpdateOne) ClearSpokenLanguages() *ProviderProfileUpdateOne {
	_u.mutation.ClearSpokenLanguages()
	return _u
}

// RemoveSpokenLanguageIDs removes the "spoken_languages" edge to SpokenLanguage entities by IDs.
func (_u *ProviderProfileUpdateOne) RemoveSpokenLanguageIDs(ids ...string) *ProviderProfileUpdateOne {
	_u.mutation.RemoveSpokenLanguageIDs(ids...)
	return _u
}

// RemoveSpokenLanguages removes "spoken_languages" edges to SpokenLanguage entities.
func (_u *ProviderProfileUpdateOne) RemoveSpokenLanguages(v ...*SpokenLanguage) *ProviderProfileUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSpokenLanguageIDs(ids...)
}

// Where appends a list predicates to the ProviderProfileUpdate builder.
func (_u *ProviderProfileUpdateOne) Where(ps ...predicate.ProviderProfile) *ProviderProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderProfileUpdateOne) Select(field string, fields ...string) *ProviderProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProviderProfile entity.
func (_u *ProviderProfileUpdateOne) Save(ctx context.Context) (*ProviderProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderProfileUpdateOne) SaveX(ctx context.Context) *ProviderProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providerprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderProfileUpdateOne) check() error {
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := providerprofile.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ProviderProfile.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := providerprofile.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "ProviderProfile.provider_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bio(); ok {
		if err := providerprofile.BioValidator(v); err != nil {
			return &ValidationError{Name: "bio", err: fmt.Errorf(`ent: validator failed for field "ProviderProfile.bio": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxTravelDistanceKm(); ok {
		if err := providerprofile.MaxTravelDistanceKmValidator(v); err != nil {
			return &ValidationError{Name: "max_travel_distance_km", err: fmt.Errorf(`ent: validator failed for field "ProviderProfile.max_travel_distance_km": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderProfileUpdateOne) sqlSave(ctx context.Context) (_node *ProviderProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerprofile.Table, providerprofile.Columns, sqlgraph.NewFieldSpec(providerprofile.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProviderProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providerprofile.FieldID)
		for _, f := range fields {
			if !providerprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != providerprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(providerprofile.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(providerprofile.FieldProviderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bio(); ok {
		_spec.SetField(providerprofile.FieldBio, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrimaryLocalityID(); ok {
		_spec.SetField(providerprofile.FieldPrimaryLocalityID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.MaxTravelDistanceKm(); ok {
		_spec.SetField(providerprofile.FieldMaxTravelDistanceKm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTravelDistanceKm(); ok {
		_spec.AddField(providerprofile.FieldMaxTravelDistanceKm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TravelsToCustomer(); ok {
		_spec.SetField(providerprofile.FieldTravelsToCustomer, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReceivesCustomer(); ok {
		_spec.SetField(providerprofile.FieldReceivesCustomer, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RemoteServices(); ok {
		_spec.SetField(providerprofile.FieldRemoteServices, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providerprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ServiceLocalitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   providerprofile.ServiceLocalitiesTable,
			Columns: providerprofile.ServiceLocalitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locality.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedServiceLocalitiesIDs(); len(nodes) > 0 && !_u.mutation.ServiceLocalitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   providerprofile.ServiceLocalitiesTable,
			Columns: providerprofile.ServiceLocalitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locality.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServiceLocalitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   providerprofile.ServiceLocalitiesTable,
			Columns: providerprofile.ServiceLocalitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locality.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SpokenLanguagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   providerprofile.SpokenLanguagesTable,
			Columns: providerprofile.SpokenLanguagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spokenlanguage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSpokenLanguagesIDs(); len(nodes) > 0 && !_u.mutation.SpokenLanguagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   providerprofile.SpokenLanguagesTable,
			Columns: providerprofile.SpokenLanguagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spokenlanguage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SpokenLanguagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   providerprofile.SpokenLanguagesTable,
			Columns: providerprofile.SpokenLanguagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spokenlanguage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProviderProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
