// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/locality"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/providerprofile"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/providerservicelocality"
	"github.com/google/uuid"
)

// ProviderServiceLocality is the model entity for the ProviderServiceLocality schema.
type ProviderServiceLocality struct {
	config `json:"-"`
	// InternalUserID holds the value of the "internal_user_id" field.
	InternalUserID uuid.UUID `json:"internal_user_id,omitempty"`
	// LocalityID holds the value of the "locality_id" field.
	LocalityID uuid.UUID `json:"locality_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProviderServiceLocalityQuery when eager-loading is set.
	Edges        ProviderServiceLocalityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProviderServiceLocalityEdges holds the relations/edges for other nodes in the graph.
type ProviderServiceLocalityEdges struct {
	// Profile holds the value of the profile edge.
	Profile *ProviderProfile `json:"profile,omitempty"`
	// Locality holds the value of the locality edge.
	Locality *Locality `json:"locality,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProfileOrErr returns the Profile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProviderServiceLocalityEdges) ProfileOrErr() (*ProviderProfile, error) {
	if e.Profile != nil {
		return e.Profile, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: providerprofile.Label}
	}
	return nil, &NotLoadedError{edge: "profile"}
}

// LocalityOrErr returns the Locality value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProviderServiceLocalityEdges) LocalityOrErr() (*Locality, error) {
	if e.Locality != nil {
		return e.Locality, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: locality.Label}
	}
	return nil, &NotLoadedError{edge: "locality"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderServiceLocality) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providerservicelocality.FieldInternalUserID, providerservicelocality.FieldLocalityID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderServiceLocality fields.
func (_m *ProviderServiceLocality) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providerservicelocality.FieldInternalUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field internal_user_id", values[i])
			} else if value != nil {
				_m.InternalUserID = *value
			}
		case providerservicelocality.FieldLocalityID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field locality_id", values[i])
			} else if value != nil {
				_m.LocalityID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderServiceLocality.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderServiceLocality) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProfile queries the "profile" edge of the ProviderServiceLocality entity.
func (_m *ProviderServiceLocality) QueryProfile() *ProviderProfileQuery {
	return NewProviderServiceLocalityClient(_m.config).QueryProfile(_m)
}

// QueryLocality queries the "locality" edge of the ProviderServiceLocality entity.
func (_m *ProviderServiceLocality) QueryLocality() *LocalityQuery {
	return NewProviderServiceLocalityClient(_m.config).QueryLocality(_m)
}

// Update returns a builder for updating this ProviderServiceLocality.
// Note that you need to call ProviderServiceLocality.Unwrap() before calling this method if this ProviderServiceLocality
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderServiceLocality) Update() *ProviderServiceLocalityUpdateOne {
	return NewProviderServiceLocalityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderServiceLocality entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderServiceLocality) Unwrap() *ProviderServiceLocality {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderServiceLocality is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderServiceLocality) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderServiceLocality(")
	builder.WriteString("internal_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InternalUserID))
	builder.WriteString(", ")
	builder.WriteString("locality_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LocalityID))
	builder.WriteByte(')')
	return builder.String()
}

// ProviderServiceLocalities is a parsable slice of ProviderServiceLocality.
type ProviderServiceLocalities []*ProviderServiceLocality
