// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/providercontactchannel"
	"github.com/google/uuid"
)

// ProviderContactChannel is the model entity for the ProviderContactChannel schema.
type ProviderContactChannel struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// InternalUserID holds the value of the "internal_user_id" field.
	InternalUserID uuid.UUID `json:"internal_user_id,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel providercontactchannel.Channel `json:"channel,omitempty"`
	// Ciphertext holds the value of the "ciphertext" field.
	Ciphertext []byte `json:"ciphertext,omitempty"`
	// Nonce holds the value of the "nonce" field.
	Nonce []byte `json:"nonce,omitempty"`
	// KeyVersion holds the value of the "key_version" field.
	KeyVersion string `json:"key_version,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// RevealConsent holds the value of the "reveal_consent" field.
	RevealConsent bool `json:"reveal_consent,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderContactChannel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providercontactchannel.FieldCiphertext, providercontactchannel.FieldNonce:
			values[i] = new([]byte)
		case providercontactchannel.FieldEnabled, providercontactchannel.FieldRevealConsent:
			values[i] = new(sql.NullBool)
		case providercontactchannel.FieldChannel, providercontactchannel.FieldKeyVersion:
			values[i] = new(sql.NullString)
		case providercontactchannel.FieldCreatedAt, providercontactchannel.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case providercontactchannel.FieldID, providercontactchannel.FieldInternalUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderContactChannel fields.
func (_m *ProviderContactChannel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providercontactchannel.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case providercontactchannel.FieldInternalUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field internal_user_id", values[i])
			} else if value != nil {
				_m.InternalUserID = *value
			}
		case providercontactchannel.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = providercontactchannel.Channel(value.String)
			}
		case providercontactchannel.FieldCiphertext:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ciphertext", values[i])
			} else if value != nil {
				_m.Ciphertext = *value
			}
		case providercontactchannel.FieldNonce:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field nonce", values[i])
			} else if value != nil {
				_m.Nonce = *value
			}
		case providercontactchannel.FieldKeyVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_version", values[i])
			} else if value.Valid {
				_m.KeyVersion = value.String
			}
		case providercontactchannel.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case providercontactchannel.FieldRevealConsent:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field reveal_consent", values[i])
			} else if value.Valid {
				_m.RevealConsent = value.Bool
			}
		case providercontactchannel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case providercontactchannel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderContactChannel.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderContactChannel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProviderContactChannel.
// Note that you need to call ProviderContactChannel.Unwrap() before calling this method if this ProviderContactChannel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderContactChannel) Update() *ProviderContactChannelUpdateOne {
	return NewProviderContactChannelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderContactChannel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderContactChannel) Unwrap() *ProviderContactChannel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderContactChannel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderContactChannel) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderContactChannel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("internal_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InternalUserID))
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(fmt.Sprintf("%v", _m.Channel))
	builder.WriteString(", ")
	builder.WriteString("ciphertext=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ciphertext))
	builder.WriteString(", ")
	builder.WriteString("nonce=")
	builder.WriteString(fmt.Sprintf("%v", _m.Nonce))
	builder.WriteString(", ")
	builder.WriteString("key_version=")
	builder.WriteString(_m.KeyVersion)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("reveal_consent=")
	builder.WriteString(fmt.Sprintf("%v", _m.RevealConsent))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProviderContactChannels is a parsable slice of ProviderContactChannel.
type ProviderContactChannels []*ProviderContactChannel
