// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/predicate"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/servicecategory"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/servicecategorytranslation"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/supportedlocale"
	"github.com/google/uuid"
)

// ServiceCategoryTranslationQuery is the builder for querying ServiceCategoryTranslation entities.
type ServiceCategoryTranslationQuery struct {
	config
	ctx              *QueryContext
	order            []servicecategorytranslation.OrderOption
	inters           []Interceptor
	predicates       []predicate.ServiceCategoryTranslation
	withCategory     *ServiceCategoryQuery
	withLocaleRecord *SupportedLocaleQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ServiceCategoryTranslationQuery builder.
func (_q *ServiceCategoryTranslationQuery) Where(ps ...predicate.ServiceCategoryTranslation) *ServiceCategoryTranslationQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ServiceCategoryTranslationQuery) Limit(limit int) *ServiceCategoryTranslationQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ServiceCategoryTranslationQuery) Offset(offset int) *ServiceCategoryTranslationQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ServiceCategoryTranslationQuery) Unique(unique bool) *ServiceCategoryTranslationQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ServiceCategoryTranslationQuery) Order(o ...servicecategorytranslation.OrderOption) *ServiceCategoryTranslationQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCategory chains the current query on the "category" edge.
func (_q *ServiceCategoryTranslationQuery) QueryCategory() *ServiceCategoryQuery {
	query := (&ServiceCategoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(servicecategorytranslation.Table, servicecategorytranslation.CategoryColumn, selector),
			sqlgraph.To(servicecategory.Table, servicecategory.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, servicecategorytranslation.CategoryTable, servicecategorytranslation.CategoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLocaleRecord chains the current query on the "locale_record" edge.
func (_q *ServiceCategoryTranslationQuery) QueryLocaleRecord() *SupportedLocaleQuery {
	query := (&SupportedLocaleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(servicecategorytranslation.Table, servicecategorytranslation.LocaleRecordColumn, selector),
			sqlgraph.To(supportedlocale.Table, supportedlocale.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, servicecategorytranslation.LocaleRecordTable, servicecategorytranslation.LocaleRecordColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ServiceCategoryTranslation entity from the query.
// Returns a *NotFoundError when no ServiceCategoryTranslation was found.
func (_q *ServiceCategoryTranslationQuery) First(ctx context.Context) (*ServiceCategoryTranslation, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{servicecategorytranslation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ServiceCategoryTranslationQuery) FirstX(ctx context.Context) *ServiceCategoryTranslation {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single ServiceCategoryTranslation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ServiceCategoryTranslation entity is found.
// Returns a *NotFoundError when no ServiceCategoryTranslation entities are found.
func (_q *ServiceCategoryTranslationQuery) Only(ctx context.Context) (*ServiceCategoryTranslation, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{servicecategorytranslation.Label}
	default:
		return nil, &NotSingularError{servicecategorytranslation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ServiceCategoryTranslationQuery) OnlyX(ctx context.Context) *ServiceCategoryTranslation {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of ServiceCategoryTranslations.
func (_q *ServiceCategoryTranslationQuery) All(ctx context.Context) ([]*ServiceCategoryTranslation, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ServiceCategoryTranslation, *ServiceCategoryTranslationQuery]()
	return withInterceptors[[]*ServiceCategoryTranslation](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ServiceCategoryTranslationQuery) AllX(ctx context.Context) []*ServiceCategoryTranslation {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (_q *ServiceCategoryTranslationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ServiceCategoryTranslationQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ServiceCategoryTranslationQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ServiceCategoryTranslationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ServiceCategoryTranslationQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ServiceCategoryTranslationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ServiceCategoryTranslationQuery) Clone() *ServiceCategoryTranslationQuery {
	if _q == nil {
		return nil
	}
	return &ServiceCategoryTranslationQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]servicecategorytranslation.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.ServiceCategoryTranslation{}, _q.predicates...),
		withCategory:     _q.withCategory.Clone(),
		withLocaleRecord: _q.withLocaleRecord.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCategory tells the query-builder to eager-load the nodes that are connected to
// the "category" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ServiceCategoryTranslationQuery) WithCategory(opts ...func(*ServiceCategoryQuery)) *ServiceCategoryTranslationQuery {
	query := (&ServiceCategoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCategory = query
	return _q
}

// WithLocaleRecord tells the query-builder to eager-load the nodes that are connected to
// the "locale_record" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ServiceCategoryTranslationQuery) WithLocaleRecord(opts ...func(*SupportedLocaleQuery)) *ServiceCategoryTranslationQuery {
	query := (&SupportedLocaleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLocaleRecord = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CategoryID uuid.UUID `json:"category_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ServiceCategoryTranslation.Query().
//		GroupBy(servicecategorytranslation.FieldCategoryID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ServiceCategoryTranslationQuery) GroupBy(field string, fields ...string) *ServiceCategoryTranslationGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ServiceCategoryTranslationGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = servicecategorytranslation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CategoryID uuid.UUID `json:"category_id,omitempty"`
//	}
//
//	client.ServiceCategoryTranslation.Query().
//		Select(servicecategorytranslation.FieldCategoryID).
//		Scan(ctx, &v)
func (_q *ServiceCategoryTranslationQuery) Select(fields ...string) *ServiceCategoryTranslationSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ServiceCategoryTranslationSelect{ServiceCategoryTranslationQuery: _q}
	sbuild.label = servicecategorytranslation.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ServiceCategoryTranslationSelect configured with the given aggregations.
func (_q *ServiceCategoryTranslationQuery) Aggregate(fns ...AggregateFunc) *ServiceCategoryTranslationSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ServiceCategoryTranslationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !servicecategorytranslation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ServiceCategoryTranslationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ServiceCategoryTranslation, error) {
	var (
		nodes       = []*ServiceCategoryTranslation{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withCategory != nil,
			_q.withLocaleRecord != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ServiceCategoryTranslation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ServiceCategoryTranslation{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCategory; query != nil {
		if err := _q.loadCategory(ctx, query, nodes, nil,
			func(n *ServiceCategoryTranslation, e *ServiceCategory) { n.Edges.Category = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLocaleRecord; query != nil {
		if err := _q.loadLocaleRecord(ctx, query, nodes, nil,
			func(n *ServiceCategoryTranslation, e *SupportedLocale) { n.Edges.LocaleRecord = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ServiceCategoryTranslationQuery) loadCategory(ctx context.Context, query *ServiceCategoryQuery, nodes []*ServiceCategoryTranslation, init func(*ServiceCategoryTranslation), assign func(*ServiceCategoryTranslation, *ServiceCategory)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ServiceCategoryTranslation)
	for i := range nodes {
		fk := nodes[i].CategoryID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(servicecategory.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "category_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ServiceCategoryTranslationQuery) loadLocaleRecord(ctx context.Context, query *SupportedLocaleQuery, nodes []*ServiceCategoryTranslation, init func(*ServiceCategoryTranslation), assign func(*ServiceCategoryTranslation, *SupportedLocale)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*ServiceCategoryTranslation)
	for i := range nodes {
		fk := nodes[i].Locale
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(supportedlocale.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "locale" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ServiceCategoryTranslationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ServiceCategoryTranslationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(servicecategorytranslation.Table, servicecategorytranslation.Columns, nil)
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if _q.withCategory != nil {
			_spec.Node.AddColumnOnce(servicecategorytranslation.FieldCategoryID)
		}
		if _q.withLocaleRecord != nil {
			_spec.Node.AddColumnOnce(servicecategorytranslation.FieldLocale)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ServiceCategoryTranslationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(servicecategorytranslation.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = servicecategorytranslation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ServiceCategoryTranslationGroupBy is the group-by builder for ServiceCategoryTranslation entities.
type ServiceCategoryTranslationGroupBy struct {
	selector
	build *ServiceCategoryTranslationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ServiceCategoryTranslationGroupBy) Aggregate(fns ...AggregateFunc) *ServiceCategoryTranslationGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ServiceCategoryTranslationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ServiceCategoryTranslationQuery, *ServiceCategoryTranslationGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ServiceCategoryTranslationGroupBy) sqlScan(ctx context.Context, root *ServiceCategoryTranslationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ServiceCategoryTranslationSelect is the builder for selecting fields of ServiceCategoryTranslation entities.
type ServiceCategoryTranslationSelect struct {
	*ServiceCategoryTranslationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ServiceCategoryTranslationSelect) Aggregate(fns ...AggregateFunc) *ServiceCategoryTranslationSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ServiceCategoryTranslationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ServiceCategoryTranslationQuery, *ServiceCategoryTranslationSelect](ctx, _s.ServiceCategoryTranslationQuery, _s, _s.inters, v)
}

func (_s *ServiceCategoryTranslationSelect) sqlScan(ctx context.Context, root *ServiceCategoryTranslationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
