// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/predicate"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/servicecategorytranslation"
)

// ServiceCategoryTranslationUpdate is the builder for updating ServiceCategoryTranslation entities.
type ServiceCategoryTranslationUpdate struct {
	config
	hooks    []Hook
	mutation *ServiceCategoryTranslationMutation
}

// Where appends a list predicates to the ServiceCategoryTranslationUpdate builder.
func (_u *ServiceCategoryTranslationUpdate) Where(ps ...predicate.ServiceCategoryTranslation) *ServiceCategoryTranslationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ServiceCategoryTranslationUpdate) SetName(v string) *ServiceCategoryTranslationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ServiceCategoryTranslationUpdate) SetNillableName(v *string) *ServiceCategoryTranslationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ServiceCategoryTranslationUpdate) SetDescription(v string) *ServiceCategoryTranslationUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ServiceCategoryTranslationUpdate) SetNillableDescription(v *string) *ServiceCategoryTranslationUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ServiceCategoryTranslationUpdate) ClearDescription() *ServiceCategoryTranslationUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the ServiceCategoryTranslationMutation object of the builder.
func (_u *ServiceCategoryTranslationUpdate) Mutation() *ServiceCategoryTranslationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServiceCategoryTranslationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceCategoryTranslationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServiceCategoryTranslationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceCategoryTranslationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceCategoryTranslationUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := servicecategorytranslation.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ServiceCategoryTranslation.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := servicecategorytranslation.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ServiceCategoryTranslation.description": %w`, err)}
		}
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServiceCategoryTranslation.category"`)
	}
	if _u.mutation.LocaleRecordCleared() && len(_u.mutation.LocaleRecordIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServiceCategoryTranslation.locale_record"`)
	}
	return nil
}

func (_u *ServiceCategoryTranslationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(servicecategorytranslation.Table, servicecategorytranslation.Columns, sqlgraph.NewFieldSpec(servicecategorytranslation.FieldCategoryID, field.TypeUUID), sqlgraph.NewFieldSpec(servicecategorytranslation.FieldLocale, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(servicecategorytranslation.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(servicecategorytranslation.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(servicecategorytranslation.FieldDescription, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servicecategorytranslation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServiceCategoryTranslationUpdateOne is the builder for updating a single ServiceCategoryTranslation entity.
type ServiceCategoryTranslationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServiceCategoryTranslationMutation
}

// SetName sets the "name" field.
func (_u *ServiceCategoryTranslationUpdateOne) SetName(v string) *ServiceCategoryTranslationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ServiceCategoryTranslationUpdateOne) SetNillableName(v *string) *ServiceCategoryTranslationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ServiceCategoryTranslationUpdateOne) SetDescription(v string) *ServiceCategoryTranslationUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ServiceCategoryTranslationUpdateOne) SetNillableDescription(v *string) *ServiceCategoryTranslationUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ServiceCategoryTranslationUpdateOne) ClearDescription() *ServiceCategoryTranslationUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the ServiceCategoryTranslationMutation object of the builder.
func (_u *ServiceCategoryTranslationUpdateOne) Mutation() *ServiceCategoryTranslationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ServiceCategoryTranslationUpdate builder.
func (_u *ServiceCategoryTranslationUpdateOne) Where(ps ...predicate.ServiceCategoryTranslation) *ServiceCategoryTranslationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServiceCategoryTranslationUpdateOne) Select(field string, fields ...string) *ServiceCategoryTranslationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ServiceCategoryTranslation entity.
func (_u *ServiceCategoryTranslationUpdateOne) Save(ctx context.Context) (*ServiceCategoryTranslation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceCategoryTranslationUpdateOne) SaveX(ctx context.Context) *ServiceCategoryTranslation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServiceCategoryTranslationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceCategoryTranslationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceCategoryTranslationUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := servicecategorytranslation.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ServiceCategoryTranslation.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := servicecategorytranslation.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ServiceCategoryTranslation.description": %w`, err)}
		}
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServiceCategoryTranslation.category"`)
	}
	if _u.mutation.LocaleRecordCleared() && len(_u.mutation.LocaleRecordIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServiceCategoryTranslation.locale_record"`)
	}
	return nil
}

func (_u *ServiceCategoryTranslationUpdateOne) sqlSave(ctx context.Context) (_node *ServiceCategoryTranslation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(servicecategorytranslation.Table, servicecategorytranslation.Columns, sqlgraph.NewFieldSpec(servicecategorytranslation.FieldCategoryID, field.TypeUUID), sqlgraph.NewFieldSpec(servicecategorytranslation.FieldLocale, field.TypeString))
	if id, ok := _u.mutation.CategoryID(); !ok {
		return nil, &ValidationError{Name: "category_id", err: errors.New(`ent: missing "ServiceCategoryTranslation.category_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.Locale(); !ok {
		return nil, &ValidationError{Name: "locale", err: errors.New(`ent: missing "ServiceCategoryTranslation.locale" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !servicecategorytranslation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(servicecategorytranslation.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(servicecategorytranslation.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(servicecategorytranslation.FieldDescription, field.TypeString)
	}
	_node = &ServiceCategoryTranslation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servicecategorytranslation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
