// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/spokenlanguage"
)

// SpokenLanguage is the model entity for the SpokenLanguage schema.
type SpokenLanguage struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SpokenLanguageQuery when eager-loading is set.
	Edges        SpokenLanguageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SpokenLanguageEdges holds the relations/edges for other nodes in the graph.
type SpokenLanguageEdges struct {
	// LocalizedIn holds the value of the localized_in edge.
	LocalizedIn []*SupportedLocale `json:"localized_in,omitempty"`
	// ProviderProfiles holds the value of the provider_profiles edge.
	ProviderProfiles []*ProviderProfile `json:"provider_profiles,omitempty"`
	// Translations holds the value of the translations edge.
	Translations []*SpokenLanguageTranslation `json:"translations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// LocalizedInOrErr returns the LocalizedIn value or an error if the edge
// was not loaded in eager-loading.
func (e SpokenLanguageEdges) LocalizedInOrErr() ([]*SupportedLocale, error) {
	if e.loadedTypes[0] {
		return e.LocalizedIn, nil
	}
	return nil, &NotLoadedError{edge: "localized_in"}
}

// ProviderProfilesOrErr returns the ProviderProfiles value or an error if the edge
// was not loaded in eager-loading.
func (e SpokenLanguageEdges) ProviderProfilesOrErr() ([]*ProviderProfile, error) {
	if e.loadedTypes[1] {
		return e.ProviderProfiles, nil
	}
	return nil, &NotLoadedError{edge: "provider_profiles"}
}

// TranslationsOrErr returns the Translations value or an error if the edge
// was not loaded in eager-loading.
func (e SpokenLanguageEdges) TranslationsOrErr() ([]*SpokenLanguageTranslation, error) {
	if e.loadedTypes[2] {
		return e.Translations, nil
	}
	return nil, &NotLoadedError{edge: "translations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SpokenLanguage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case spokenlanguage.FieldActive:
			values[i] = new(sql.NullBool)
		case spokenlanguage.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case spokenlanguage.FieldID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SpokenLanguage fields.
func (_m *SpokenLanguage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case spokenlanguage.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case spokenlanguage.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case spokenlanguage.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SpokenLanguage.
// This includes values selected through modifiers, order, etc.
func (_m *SpokenLanguage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLocalizedIn queries the "localized_in" edge of the SpokenLanguage entity.
func (_m *SpokenLanguage) QueryLocalizedIn() *SupportedLocaleQuery {
	return NewSpokenLanguageClient(_m.config).QueryLocalizedIn(_m)
}

// QueryProviderProfiles queries the "provider_profiles" edge of the SpokenLanguage entity.
func (_m *SpokenLanguage) QueryProviderProfiles() *ProviderProfileQuery {
	return NewSpokenLanguageClient(_m.config).QueryProviderProfiles(_m)
}

// QueryTranslations queries the "translations" edge of the SpokenLanguage entity.
func (_m *SpokenLanguage) QueryTranslations() *SpokenLanguageTranslationQuery {
	return NewSpokenLanguageClient(_m.config).QueryTranslations(_m)
}

// Update returns a builder for updating this SpokenLanguage.
// Note that you need to call SpokenLanguage.Unwrap() before calling this method if this SpokenLanguage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SpokenLanguage) Update() *SpokenLanguageUpdateOne {
	return NewSpokenLanguageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SpokenLanguage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SpokenLanguage) Unwrap() *SpokenLanguage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SpokenLanguage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SpokenLanguage) String() string {
	var builder strings.Builder
	builder.WriteString("SpokenLanguage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// SpokenLanguages is a parsable slice of SpokenLanguage.
type SpokenLanguages []*SpokenLanguage
