// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/predicate"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/providerprofile"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/spokenlanguage"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/spokenlanguagetranslation"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/supportedlocale"
	"github.com/google/uuid"
)

// SpokenLanguageQuery is the builder for querying SpokenLanguage entities.
type SpokenLanguageQuery struct {
	config
	ctx                  *QueryContext
	order                []spokenlanguage.OrderOption
	inters               []Interceptor
	predicates           []predicate.SpokenLanguage
	withLocalizedIn      *SupportedLocaleQuery
	withProviderProfiles *ProviderProfileQuery
	withTranslations     *SpokenLanguageTranslationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SpokenLanguageQuery builder.
func (_q *SpokenLanguageQuery) Where(ps ...predicate.SpokenLanguage) *SpokenLanguageQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SpokenLanguageQuery) Limit(limit int) *SpokenLanguageQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SpokenLanguageQuery) Offset(offset int) *SpokenLanguageQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SpokenLanguageQuery) Unique(unique bool) *SpokenLanguageQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SpokenLanguageQuery) Order(o ...spokenlanguage.OrderOption) *SpokenLanguageQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryLocalizedIn chains the current query on the "localized_in" edge.
func (_q *SpokenLanguageQuery) QueryLocalizedIn() *SupportedLocaleQuery {
	query := (&SupportedLocaleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(spokenlanguage.Table, spokenlanguage.FieldID, selector),
			sqlgraph.To(supportedlocale.Table, supportedlocale.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, spokenlanguage.LocalizedInTable, spokenlanguage.LocalizedInPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProviderProfiles chains the current query on the "provider_profiles" edge.
func (_q *SpokenLanguageQuery) QueryProviderProfiles() *ProviderProfileQuery {
	query := (&ProviderProfileClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(spokenlanguage.Table, spokenlanguage.FieldID, selector),
			sqlgraph.To(providerprofile.Table, providerprofile.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, spokenlanguage.ProviderProfilesTable, spokenlanguage.ProviderProfilesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTranslations chains the current query on the "translations" edge.
func (_q *SpokenLanguageQuery) QueryTranslations() *SpokenLanguageTranslationQuery {
	query := (&SpokenLanguageTranslationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(spokenlanguage.Table, spokenlanguage.FieldID, selector),
			sqlgraph.To(spokenlanguagetranslation.Table, spokenlanguagetranslation.LanguageColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, spokenlanguage.TranslationsTable, spokenlanguage.TranslationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SpokenLanguage entity from the query.
// Returns a *NotFoundError when no SpokenLanguage was found.
func (_q *SpokenLanguageQuery) First(ctx context.Context) (*SpokenLanguage, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{spokenlanguage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SpokenLanguageQuery) FirstX(ctx context.Context) *SpokenLanguage {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SpokenLanguage ID from the query.
// Returns a *NotFoundError when no SpokenLanguage ID was found.
func (_q *SpokenLanguageQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{spokenlanguage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SpokenLanguageQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SpokenLanguage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SpokenLanguage entity is found.
// Returns a *NotFoundError when no SpokenLanguage entities are found.
func (_q *SpokenLanguageQuery) Only(ctx context.Context) (*SpokenLanguage, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{spokenlanguage.Label}
	default:
		return nil, &NotSingularError{spokenlanguage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SpokenLanguageQuery) OnlyX(ctx context.Context) *SpokenLanguage {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SpokenLanguage ID in the query.
// Returns a *NotSingularError when more than one SpokenLanguage ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SpokenLanguageQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{spokenlanguage.Label}
	default:
		err = &NotSingularError{spokenlanguage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SpokenLanguageQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SpokenLanguages.
func (_q *SpokenLanguageQuery) All(ctx context.Context) ([]*SpokenLanguage, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SpokenLanguage, *SpokenLanguageQuery]()
	return withInterceptors[[]*SpokenLanguage](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SpokenLanguageQuery) AllX(ctx context.Context) []*SpokenLanguage {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SpokenLanguage IDs.
func (_q *SpokenLanguageQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(spokenlanguage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SpokenLanguageQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SpokenLanguageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SpokenLanguageQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SpokenLanguageQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SpokenLanguageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SpokenLanguageQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SpokenLanguageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SpokenLanguageQuery) Clone() *SpokenLanguageQuery {
	if _q == nil {
		return nil
	}
	return &SpokenLanguageQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]spokenlanguage.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.SpokenLanguage{}, _q.predicates...),
		withLocalizedIn:      _q.withLocalizedIn.Clone(),
		withProviderProfiles: _q.withProviderProfiles.Clone(),
		withTranslations:     _q.withTranslations.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithLocalizedIn tells the query-builder to eager-load the nodes that are connected to
// the "localized_in" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SpokenLanguageQuery) WithLocalizedIn(opts ...func(*SupportedLocaleQuery)) *SpokenLanguageQuery {
	query := (&SupportedLocaleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLocalizedIn = query
	return _q
}

// WithProviderProfiles tells the query-builder to eager-load the nodes that are connected to
// the "provider_profiles" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SpokenLanguageQuery) WithProviderProfiles(opts ...func(*ProviderProfileQuery)) *SpokenLanguageQuery {
	query := (&ProviderProfileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProviderProfiles = query
	return _q
}

// WithTranslations tells the query-builder to eager-load the nodes that are connected to
// the "translations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SpokenLanguageQuery) WithTranslations(opts ...func(*SpokenLanguageTranslationQuery)) *SpokenLanguageQuery {
	query := (&SpokenLanguageTranslationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTranslations = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Active bool `json:"active,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SpokenLanguage.Query().
//		GroupBy(spokenlanguage.FieldActive).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SpokenLanguageQuery) GroupBy(field string, fields ...string) *SpokenLanguageGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SpokenLanguageGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = spokenlanguage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Active bool `json:"active,omitempty"`
//	}
//
//	client.SpokenLanguage.Query().
//		Select(spokenlanguage.FieldActive).
//		Scan(ctx, &v)
func (_q *SpokenLanguageQuery) Select(fields ...string) *SpokenLanguageSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SpokenLanguageSelect{SpokenLanguageQuery: _q}
	sbuild.label = spokenlanguage.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SpokenLanguageSelect configured with the given aggregations.
func (_q *SpokenLanguageQuery) Aggregate(fns ...AggregateFunc) *SpokenLanguageSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SpokenLanguageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !spokenlanguage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SpokenLanguageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SpokenLanguage, error) {
	var (
		nodes       = []*SpokenLanguage{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withLocalizedIn != nil,
			_q.withProviderProfiles != nil,
			_q.withTranslations != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SpokenLanguage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SpokenLanguage{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withLocalizedIn; query != nil {
		if err := _q.loadLocalizedIn(ctx, query, nodes,
			func(n *SpokenLanguage) { n.Edges.LocalizedIn = []*SupportedLocale{} },
			func(n *SpokenLanguage, e *SupportedLocale) { n.Edges.LocalizedIn = append(n.Edges.LocalizedIn, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProviderProfiles; query != nil {
		if err := _q.loadProviderProfiles(ctx, query, nodes,
			func(n *SpokenLanguage) { n.Edges.ProviderProfiles = []*ProviderProfile{} },
			func(n *SpokenLanguage, e *ProviderProfile) {
				n.Edges.ProviderProfiles = append(n.Edges.ProviderProfiles, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withTranslations; query != nil {
		if err := _q.loadTranslations(ctx, query, nodes,
			func(n *SpokenLanguage) { n.Edges.Translations = []*SpokenLanguageTranslation{} },
			func(n *SpokenLanguage, e *SpokenLanguageTranslation) {
				n.Edges.Translations = append(n.Edges.Translations, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SpokenLanguageQuery) loadLocalizedIn(ctx context.Context, query *SupportedLocaleQuery, nodes []*SpokenLanguage, init func(*SpokenLanguage), assign func(*SpokenLanguage, *SupportedLocale)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[string]*SpokenLanguage)
	nids := make(map[string]map[*SpokenLanguage]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(spokenlanguage.LocalizedInTable)
		s.Join(joinT).On(s.C(supportedlocale.FieldID), joinT.C(spokenlanguage.LocalizedInPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(spokenlanguage.LocalizedInPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(spokenlanguage.LocalizedInPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullString)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullString).String
				inValue := values[1].(*sql.NullString).String
				if nids[inValue] == nil {
					nids[inValue] = map[*SpokenLanguage]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*SupportedLocale](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "localized_in" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *SpokenLanguageQuery) loadProviderProfiles(ctx context.Context, query *ProviderProfileQuery, nodes []*SpokenLanguage, init func(*SpokenLanguage), assign func(*SpokenLanguage, *ProviderProfile)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[string]*SpokenLanguage)
	nids := make(map[uuid.UUID]map[*SpokenLanguage]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(spokenlanguage.ProviderProfilesTable)
		s.Join(joinT).On(s.C(providerprofile.FieldID), joinT.C(spokenlanguage.ProviderProfilesPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(spokenlanguage.ProviderProfilesPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(spokenlanguage.ProviderProfilesPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullString)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullString).String
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*SpokenLanguage]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*ProviderProfile](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "provider_profiles" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *SpokenLanguageQuery) loadTranslations(ctx context.Context, query *SpokenLanguageTranslationQuery, nodes []*SpokenLanguage, init func(*SpokenLanguage), assign func(*SpokenLanguage, *SpokenLanguageTranslation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*SpokenLanguage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(spokenlanguagetranslation.FieldLanguageCode)
	}
	query.Where(predicate.SpokenLanguageTranslation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(spokenlanguage.TranslationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LanguageCode
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "language_code" returned %v for node %v`, fk, n)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SpokenLanguageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SpokenLanguageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(spokenlanguage.Table, spokenlanguage.Columns, sqlgraph.NewFieldSpec(spokenlanguage.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, spokenlanguage.FieldID)
		for i := range fields {
			if fields[i] != spokenlanguage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SpokenLanguageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(spokenlanguage.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = spokenlanguage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SpokenLanguageGroupBy is the group-by builder for SpokenLanguage entities.
type SpokenLanguageGroupBy struct {
	selector
	build *SpokenLanguageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SpokenLanguageGroupBy) Aggregate(fns ...AggregateFunc) *SpokenLanguageGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SpokenLanguageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SpokenLanguageQuery, *SpokenLanguageGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SpokenLanguageGroupBy) sqlScan(ctx context.Context, root *SpokenLanguageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SpokenLanguageSelect is the builder for selecting fields of SpokenLanguage entities.
type SpokenLanguageSelect struct {
	*SpokenLanguageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SpokenLanguageSelect) Aggregate(fns ...AggregateFunc) *SpokenLanguageSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SpokenLanguageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SpokenLanguageQuery, *SpokenLanguageSelect](ctx, _s.SpokenLanguageQuery, _s, _s.inters, v)
}

func (_s *SpokenLanguageSelect) sqlScan(ctx context.Context, root *SpokenLanguageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
