// Code generated by ent, DO NOT EDIT.

package providerprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the providerprofile type in the database.
	Label = "provider_profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "internal_user_id"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldProviderType holds the string denoting the provider_type field in the database.
	FieldProviderType = "provider_type"
	// FieldBio holds the string denoting the bio field in the database.
	FieldBio = "bio"
	// FieldPrimaryLocalityID holds the string denoting the primary_locality_id field in the database.
	FieldPrimaryLocalityID = "primary_locality_id"
	// FieldMaxTravelDistanceKm holds the string denoting the max_travel_distance_km field in the database.
	FieldMaxTravelDistanceKm = "max_travel_distance_km"
	// FieldTravelsToCustomer holds the string denoting the travels_to_customer field in the database.
	FieldTravelsToCustomer = "travels_to_customer"
	// FieldReceivesCustomer holds the string denoting the receives_customer field in the database.
	FieldReceivesCustomer = "receives_customer"
	// FieldRemoteServices holds the string denoting the remote_services field in the database.
	FieldRemoteServices = "remote_services"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeServiceLocalities holds the string denoting the service_localities edge name in mutations.
	EdgeServiceLocalities = "service_localities"
	// EdgeSpokenLanguages holds the string denoting the spoken_languages edge name in mutations.
	EdgeSpokenLanguages = "spoken_languages"
	// EdgeServiceLocalityLinks holds the string denoting the service_locality_links edge name in mutations.
	EdgeServiceLocalityLinks = "service_locality_links"
	// EdgeSpokenLanguageLinks holds the string denoting the spoken_language_links edge name in mutations.
	EdgeSpokenLanguageLinks = "spoken_language_links"
	// LocalityFieldID holds the string denoting the ID field of the Locality.
	LocalityFieldID = "id"
	// SpokenLanguageFieldID holds the string denoting the ID field of the SpokenLanguage.
	SpokenLanguageFieldID = "id"
	// Table holds the table name of the providerprofile in the database.
	Table = "provider_profiles"
	// ServiceLocalitiesTable is the table that holds the service_localities relation/edge. The primary key declared below.
	ServiceLocalitiesTable = "provider_service_localities"
	// ServiceLocalitiesInverseTable is the table name for the Locality entity.
	// It exists in this package in order to avoid circular dependency with the "locality" package.
	ServiceLocalitiesInverseTable = "localities"
	// SpokenLanguagesTable is the table that holds the spoken_languages relation/edge. The primary key declared below.
	SpokenLanguagesTable = "provider_spoken_languages"
	// SpokenLanguagesInverseTable is the table name for the SpokenLanguage entity.
	// It exists in this package in order to avoid circular dependency with the "spokenlanguage" package.
	SpokenLanguagesInverseTable = "spoken_languages"
	// ServiceLocalityLinksTable is the table that holds the service_locality_links relation/edge.
	ServiceLocalityLinksTable = "provider_service_localities"
	// ServiceLocalityLinksInverseTable is the table name for the ProviderServiceLocality entity.
	// It exists in this package in order to avoid circular dependency with the "providerservicelocality" package.
	ServiceLocalityLinksInverseTable = "provider_service_localities"
	// ServiceLocalityLinksColumn is the table column denoting the service_locality_links relation/edge.
	ServiceLocalityLinksColumn = "internal_user_id"
	// SpokenLanguageLinksTable is the table that holds the spoken_language_links relation/edge.
	SpokenLanguageLinksTable = "provider_spoken_languages"
	// SpokenLanguageLinksInverseTable is the table name for the ProviderSpokenLanguage entity.
	// It exists in this package in order to avoid circular dependency with the "providerspokenlanguage" package.
	SpokenLanguageLinksInverseTable = "provider_spoken_languages"
	// SpokenLanguageLinksColumn is the table column denoting the spoken_language_links relation/edge.
	SpokenLanguageLinksColumn = "internal_user_id"
)

// Columns holds all SQL columns for providerprofile fields.
var Columns = []string{
	FieldID,
	FieldDisplayName,
	FieldProviderType,
	FieldBio,
	FieldPrimaryLocalityID,
	FieldMaxTravelDistanceKm,
	FieldTravelsToCustomer,
	FieldReceivesCustomer,
	FieldRemoteServices,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// ServiceLocalitiesPrimaryKey and ServiceLocalitiesColumn2 are the table columns denoting the
	// primary key for the service_localities relation (M2M).
	ServiceLocalitiesPrimaryKey = []string{"internal_user_id", "locality_id"}
	// SpokenLanguagesPrimaryKey and SpokenLanguagesColumn2 are the table columns denoting the
	// primary key for the spoken_languages relation (M2M).
	SpokenLanguagesPrimaryKey = []string{"internal_user_id", "language_code"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// ProviderTypeValidator is a validator for the "provider_type" field. It is called by the builders before save.
	ProviderTypeValidator func(string) error
	// BioValidator is a validator for the "bio" field. It is called by the builders before save.
	BioValidator func(string) error
	// MaxTravelDistanceKmValidator is a validator for the "max_travel_distance_km" field. It is called by the builders before save.
	MaxTravelDistanceKmValidator func(int) error
	// DefaultTravelsToCustomer holds the default value on creation for the "travels_to_customer" field.
	DefaultTravelsToCustomer bool
	// DefaultReceivesCustomer holds the default value on creation for the "receives_customer" field.
	DefaultReceivesCustomer bool
	// DefaultRemoteServices holds the default value on creation for the "remote_services" field.
	DefaultRemoteServices bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ProviderProfile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByProviderType orders the results by the provider_type field.
func ByProviderType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderType, opts...).ToFunc()
}

// ByBio orders the results by the bio field.
func ByBio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBio, opts...).ToFunc()
}

// ByPrimaryLocalityID orders the results by the primary_locality_id field.
func ByPrimaryLocalityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrimaryLocalityID, opts...).ToFunc()
}

// ByMaxTravelDistanceKm orders the results by the max_travel_distance_km field.
func ByMaxTravelDistanceKm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxTravelDistanceKm, opts...).ToFunc()
}

// ByTravelsToCustomer orders the results by the travels_to_customer field.
func ByTravelsToCustomer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTravelsToCustomer, opts...).ToFunc()
}

// ByReceivesCustomer orders the results by the receives_customer field.
func ByReceivesCustomer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceivesCustomer, opts...).ToFunc()
}

// ByRemoteServices orders the results by the remote_services field.
func ByRemoteServices(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteServices, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByServiceLocalitiesCount orders the results by service_localities count.
func ByServiceLocalitiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newServiceLocalitiesStep(), opts...)
	}
}

// ByServiceLocalities orders the results by service_localities terms.
func ByServiceLocalities(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServiceLocalitiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySpokenLanguagesCount orders the results by spoken_languages count.
func BySpokenLanguagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSpokenLanguagesStep(), opts...)
	}
}

// BySpokenLanguages orders the results by spoken_languages terms.
func BySpokenLanguages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSpokenLanguagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByServiceLocalityLinksCount orders the results by service_locality_links count.
func ByServiceLocalityLinksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newServiceLocalityLinksStep(), opts...)
	}
}

// ByServiceLocalityLinks orders the results by service_locality_links terms.
func ByServiceLocalityLinks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServiceLocalityLinksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySpokenLanguageLinksCount orders the results by spoken_language_links count.
func BySpokenLanguageLinksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSpokenLanguageLinksStep(), opts...)
	}
}

// BySpokenLanguageLinks orders the results by spoken_language_links terms.
func BySpokenLanguageLinks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSpokenLanguageLinksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newServiceLocalitiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServiceLocalitiesInverseTable, LocalityFieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ServiceLocalitiesTable, ServiceLocalitiesPrimaryKey...),
	)
}
func newSpokenLanguagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SpokenLanguagesInverseTable, SpokenLanguageFieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, SpokenLanguagesTable, SpokenLanguagesPrimaryKey...),
	)
}
func newServiceLocalityLinksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServiceLocalityLinksInverseTable, ServiceLocalityLinksColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, ServiceLocalityLinksTable, ServiceLocalityLinksColumn),
	)
}
func newSpokenLanguageLinksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SpokenLanguageLinksInverseTable, SpokenLanguageLinksColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, SpokenLanguageLinksTable, SpokenLanguageLinksColumn),
	)
}
