// Code generated by ent, DO NOT EDIT.

package platformrole

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the platformrole type in the database.
	Label = "platform_role"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInternalUserID holds the string denoting the internal_user_id field in the database.
	FieldInternalUserID = "internal_user_id"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldGrantedAt holds the string denoting the granted_at field in the database.
	FieldGrantedAt = "granted_at"
	// Table holds the table name of the platformrole in the database.
	Table = "platform_roles"
)

// Columns holds all SQL columns for platformrole fields.
var Columns = []string{
	FieldID,
	FieldInternalUserID,
	FieldRole,
	FieldGrantedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// DefaultGrantedAt holds the default value on creation for the "granted_at" field.
	DefaultGrantedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the PlatformRole queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInternalUserID orders the results by the internal_user_id field.
func ByInternalUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInternalUserID, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByGrantedAt orders the results by the granted_at field.
func ByGrantedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantedAt, opts...).ToFunc()
}
