// Code generated by ent, DO NOT EDIT.

package contactrevealevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldLTE(FieldID, id))
}

// CustomerInternalUserID applies equality check predicate on the "customer_internal_user_id" field. It's identical to CustomerInternalUserIDEQ.
func CustomerInternalUserID(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldEQ(FieldCustomerInternalUserID, v))
}

// ProviderInternalUserID applies equality check predicate on the "provider_internal_user_id" field. It's identical to ProviderInternalUserIDEQ.
func ProviderInternalUserID(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldEQ(FieldProviderInternalUserID, v))
}

// ListingID applies equality check predicate on the "listing_id" field. It's identical to ListingIDEQ.
func ListingID(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldEQ(FieldListingID, v))
}

// UtcDay applies equality check predicate on the "utc_day" field. It's identical to UtcDayEQ.
func UtcDay(v time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldEQ(FieldUtcDay, v))
}

// RevealedAt applies equality check predicate on the "revealed_at" field. It's identical to RevealedAtEQ.
func RevealedAt(v time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldEQ(FieldRevealedAt, v))
}

// CustomerInternalUserIDEQ applies the EQ predicate on the "customer_internal_user_id" field.
func CustomerInternalUserIDEQ(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldEQ(FieldCustomerInternalUserID, v))
}

// CustomerInternalUserIDNEQ applies the NEQ predicate on the "customer_internal_user_id" field.
func CustomerInternalUserIDNEQ(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldNEQ(FieldCustomerInternalUserID, v))
}

// CustomerInternalUserIDIn applies the In predicate on the "customer_internal_user_id" field.
func CustomerInternalUserIDIn(vs ...uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldIn(FieldCustomerInternalUserID, vs...))
}

// CustomerInternalUserIDNotIn applies the NotIn predicate on the "customer_internal_user_id" field.
func CustomerInternalUserIDNotIn(vs ...uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldNotIn(FieldCustomerInternalUserID, vs...))
}

// CustomerInternalUserIDGT applies the GT predicate on the "customer_internal_user_id" field.
func CustomerInternalUserIDGT(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldGT(FieldCustomerInternalUserID, v))
}

// CustomerInternalUserIDGTE applies the GTE predicate on the "customer_internal_user_id" field.
func CustomerInternalUserIDGTE(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldGTE(FieldCustomerInternalUserID, v))
}

// CustomerInternalUserIDLT applies the LT predicate on the "customer_internal_user_id" field.
func CustomerInternalUserIDLT(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldLT(FieldCustomerInternalUserID, v))
}

// CustomerInternalUserIDLTE applies the LTE predicate on the "customer_internal_user_id" field.
func CustomerInternalUserIDLTE(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldLTE(FieldCustomerInternalUserID, v))
}

// ProviderInternalUserIDEQ applies the EQ predicate on the "provider_internal_user_id" field.
func ProviderInternalUserIDEQ(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldEQ(FieldProviderInternalUserID, v))
}

// ProviderInternalUserIDNEQ applies the NEQ predicate on the "provider_internal_user_id" field.
func ProviderInternalUserIDNEQ(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldNEQ(FieldProviderInternalUserID, v))
}

// ProviderInternalUserIDIn applies the In predicate on the "provider_internal_user_id" field.
func ProviderInternalUserIDIn(vs ...uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldIn(FieldProviderInternalUserID, vs...))
}

// ProviderInternalUserIDNotIn applies the NotIn predicate on the "provider_internal_user_id" field.
func ProviderInternalUserIDNotIn(vs ...uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldNotIn(FieldProviderInternalUserID, vs...))
}

// ProviderInternalUserIDGT applies the GT predicate on the "provider_internal_user_id" field.
func ProviderInternalUserIDGT(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldGT(FieldProviderInternalUserID, v))
}

// ProviderInternalUserIDGTE applies the GTE predicate on the "provider_internal_user_id" field.
func ProviderInternalUserIDGTE(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldGTE(FieldProviderInternalUserID, v))
}

// ProviderInternalUserIDLT applies the LT predicate on the "provider_internal_user_id" field.
func ProviderInternalUserIDLT(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldLT(FieldProviderInternalUserID, v))
}

// ProviderInternalUserIDLTE applies the LTE predicate on the "provider_internal_user_id" field.
func ProviderInternalUserIDLTE(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldLTE(FieldProviderInternalUserID, v))
}

// ListingIDEQ applies the EQ predicate on the "listing_id" field.
func ListingIDEQ(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldEQ(FieldListingID, v))
}

// ListingIDNEQ applies the NEQ predicate on the "listing_id" field.
func ListingIDNEQ(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldNEQ(FieldListingID, v))
}

// ListingIDIn applies the In predicate on the "listing_id" field.
func ListingIDIn(vs ...uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldIn(FieldListingID, vs...))
}

// ListingIDNotIn applies the NotIn predicate on the "listing_id" field.
func ListingIDNotIn(vs ...uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldNotIn(FieldListingID, vs...))
}

// ListingIDGT applies the GT predicate on the "listing_id" field.
func ListingIDGT(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldGT(FieldListingID, v))
}

// ListingIDGTE applies the GTE predicate on the "listing_id" field.
func ListingIDGTE(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldGTE(FieldListingID, v))
}

// ListingIDLT applies the LT predicate on the "listing_id" field.
func ListingIDLT(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldLT(FieldListingID, v))
}

// ListingIDLTE applies the LTE predicate on the "listing_id" field.
func ListingIDLTE(v uuid.UUID) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldLTE(FieldListingID, v))
}

// ChannelEQ applies the EQ predicate on the "channel" field.
func ChannelEQ(v Channel) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldEQ(FieldChannel, v))
}

// ChannelNEQ applies the NEQ predicate on the "channel" field.
func ChannelNEQ(v Channel) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldNEQ(FieldChannel, v))
}

// ChannelIn applies the In predicate on the "channel" field.
func ChannelIn(vs ...Channel) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldIn(FieldChannel, vs...))
}

// ChannelNotIn applies the NotIn predicate on the "channel" field.
func ChannelNotIn(vs ...Channel) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldNotIn(FieldChannel, vs...))
}

// UtcDayEQ applies the EQ predicate on the "utc_day" field.
func UtcDayEQ(v time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldEQ(FieldUtcDay, v))
}

// UtcDayNEQ applies the NEQ predicate on the "utc_day" field.
func UtcDayNEQ(v time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldNEQ(FieldUtcDay, v))
}

// UtcDayIn applies the In predicate on the "utc_day" field.
func UtcDayIn(vs ...time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldIn(FieldUtcDay, vs...))
}

// UtcDayNotIn applies the NotIn predicate on the "utc_day" field.
func UtcDayNotIn(vs ...time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldNotIn(FieldUtcDay, vs...))
}

// UtcDayGT applies the GT predicate on the "utc_day" field.
func UtcDayGT(v time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldGT(FieldUtcDay, v))
}

// UtcDayGTE applies the GTE predicate on the "utc_day" field.
func UtcDayGTE(v time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldGTE(FieldUtcDay, v))
}

// UtcDayLT applies the LT predicate on the "utc_day" field.
func UtcDayLT(v time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldLT(FieldUtcDay, v))
}

// UtcDayLTE applies the LTE predicate on the "utc_day" field.
func UtcDayLTE(v time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldLTE(FieldUtcDay, v))
}

// RevealedAtEQ applies the EQ predicate on the "revealed_at" field.
func RevealedAtEQ(v time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldEQ(FieldRevealedAt, v))
}

// RevealedAtNEQ applies the NEQ predicate on the "revealed_at" field.
func RevealedAtNEQ(v time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldNEQ(FieldRevealedAt, v))
}

// RevealedAtIn applies the In predicate on the "revealed_at" field.
func RevealedAtIn(vs ...time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldIn(FieldRevealedAt, vs...))
}

// RevealedAtNotIn applies the NotIn predicate on the "revealed_at" field.
func RevealedAtNotIn(vs ...time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldNotIn(FieldRevealedAt, vs...))
}

// RevealedAtGT applies the GT predicate on the "revealed_at" field.
func RevealedAtGT(v time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldGT(FieldRevealedAt, v))
}

// RevealedAtGTE applies the GTE predicate on the "revealed_at" field.
func RevealedAtGTE(v time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldGTE(FieldRevealedAt, v))
}

// RevealedAtLT applies the LT predicate on the "revealed_at" field.
func RevealedAtLT(v time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldLT(FieldRevealedAt, v))
}

// RevealedAtLTE applies the LTE predicate on the "revealed_at" field.
func RevealedAtLTE(v time.Time) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.FieldLTE(FieldRevealedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ContactRevealEvent) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ContactRevealEvent) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ContactRevealEvent) predicate.ContactRevealEvent {
	return predicate.ContactRevealEvent(sql.NotPredicates(p))
}
