// Code generated by ent, DO NOT EDIT.

package locality

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the locality type in the database.
	Label = "locality"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldParentParishID holds the string denoting the parent_parish_id field in the database.
	FieldParentParishID = "parent_parish_id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSourceElementID holds the string denoting the source_element_id field in the database.
	FieldSourceElementID = "source_element_id"
	// FieldSourceVersion holds the string denoting the source_version field in the database.
	FieldSourceVersion = "source_version"
	// FieldSourceRetrievedAt holds the string denoting the source_retrieved_at field in the database.
	FieldSourceRetrievedAt = "source_retrieved_at"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldLongitude holds the string denoting the longitude field in the database.
	FieldLongitude = "longitude"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeParentParish holds the string denoting the parent_parish edge name in mutations.
	EdgeParentParish = "parent_parish"
	// EdgeProviderProfiles holds the string denoting the provider_profiles edge name in mutations.
	EdgeProviderProfiles = "provider_profiles"
	// ProviderProfileFieldID holds the string denoting the ID field of the ProviderProfile.
	ProviderProfileFieldID = "internal_user_id"
	// Table holds the table name of the locality in the database.
	Table = "localities"
	// ParentParishTable is the table that holds the parent_parish relation/edge.
	ParentParishTable = "localities"
	// ParentParishInverseTable is the table name for the AdministrativeArea entity.
	// It exists in this package in order to avoid circular dependency with the "administrativearea" package.
	ParentParishInverseTable = "administrative_areas"
	// ParentParishColumn is the table column denoting the parent_parish relation/edge.
	ParentParishColumn = "parent_parish_id"
	// ProviderProfilesTable is the table that holds the provider_profiles relation/edge. The primary key declared below.
	ProviderProfilesTable = "provider_service_localities"
	// ProviderProfilesInverseTable is the table name for the ProviderProfile entity.
	// It exists in this package in order to avoid circular dependency with the "providerprofile" package.
	ProviderProfilesInverseTable = "provider_profiles"
)

// Columns holds all SQL columns for locality fields.
var Columns = []string{
	FieldID,
	FieldSlug,
	FieldName,
	FieldParentParishID,
	FieldSource,
	FieldSourceElementID,
	FieldSourceVersion,
	FieldSourceRetrievedAt,
	FieldLatitude,
	FieldLongitude,
	FieldActive,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// ProviderProfilesPrimaryKey and ProviderProfilesColumn2 are the table columns denoting the
	// primary key for the provider_profiles relation (M2M).
	ProviderProfilesPrimaryKey = []string{"internal_user_id", "locality_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// SourceElementIDValidator is a validator for the "source_element_id" field. It is called by the builders before save.
	SourceElementIDValidator func(string) error
	// SourceVersionValidator is a validator for the "source_version" field. It is called by the builders before save.
	SourceVersionValidator func(string) error
	// LatitudeValidator is a validator for the "latitude" field. It is called by the builders before save.
	LatitudeValidator func(float64) error
	// LongitudeValidator is a validator for the "longitude" field. It is called by the builders before save.
	LongitudeValidator func(float64) error
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Locality queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByParentParishID orders the results by the parent_parish_id field.
func ByParentParishID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentParishID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySourceElementID orders the results by the source_element_id field.
func BySourceElementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceElementID, opts...).ToFunc()
}

// BySourceVersion orders the results by the source_version field.
func BySourceVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceVersion, opts...).ToFunc()
}

// BySourceRetrievedAt orders the results by the source_retrieved_at field.
func BySourceRetrievedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceRetrievedAt, opts...).ToFunc()
}

// ByLatitude orders the results by the latitude field.
func ByLatitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatitude, opts...).ToFunc()
}

// ByLongitude orders the results by the longitude field.
func ByLongitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLongitude, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByParentParishField orders the results by parent_parish field.
func ByParentParishField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentParishStep(), sql.OrderByField(field, opts...))
	}
}

// ByProviderProfilesCount orders the results by provider_profiles count.
func ByProviderProfilesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProviderProfilesStep(), opts...)
	}
}

// ByProviderProfiles orders the results by provider_profiles terms.
func ByProviderProfiles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderProfilesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newParentParishStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ParentParishInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ParentParishTable, ParentParishColumn),
	)
}
func newProviderProfilesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderProfilesInverseTable, ProviderProfileFieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, ProviderProfilesTable, ProviderProfilesPrimaryKey...),
	)
}
