// Code generated by ent, DO NOT EDIT.

package locality

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Locality {
	return predicate.Locality(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Locality {
	return predicate.Locality(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Locality {
	return predicate.Locality(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Locality {
	return predicate.Locality(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Locality {
	return predicate.Locality(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Locality {
	return predicate.Locality(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Locality {
	return predicate.Locality(sql.FieldLTE(FieldID, id))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldSlug, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldName, v))
}

// ParentParishID applies equality check predicate on the "parent_parish_id" field. It's identical to ParentParishIDEQ.
func ParentParishID(v uuid.UUID) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldParentParishID, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldSource, v))
}

// SourceElementID applies equality check predicate on the "source_element_id" field. It's identical to SourceElementIDEQ.
func SourceElementID(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldSourceElementID, v))
}

// SourceVersion applies equality check predicate on the "source_version" field. It's identical to SourceVersionEQ.
func SourceVersion(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldSourceVersion, v))
}

// SourceRetrievedAt applies equality check predicate on the "source_retrieved_at" field. It's identical to SourceRetrievedAtEQ.
func SourceRetrievedAt(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldSourceRetrievedAt, v))
}

// Latitude applies equality check predicate on the "latitude" field. It's identical to LatitudeEQ.
func Latitude(v float64) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldLatitude, v))
}

// Longitude applies equality check predicate on the "longitude" field. It's identical to LongitudeEQ.
func Longitude(v float64) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldLongitude, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldUpdatedAt, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Locality {
	return predicate.Locality(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Locality {
	return predicate.Locality(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Locality {
	return predicate.Locality(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Locality {
	return predicate.Locality(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Locality {
	return predicate.Locality(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Locality {
	return predicate.Locality(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Locality {
	return predicate.Locality(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Locality {
	return predicate.Locality(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Locality {
	return predicate.Locality(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Locality {
	return predicate.Locality(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Locality {
	return predicate.Locality(sql.FieldContainsFold(FieldSlug, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Locality {
	return predicate.Locality(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Locality {
	return predicate.Locality(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Locality {
	return predicate.Locality(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Locality {
	return predicate.Locality(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Locality {
	return predicate.Locality(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Locality {
	return predicate.Locality(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Locality {
	return predicate.Locality(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Locality {
	return predicate.Locality(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Locality {
	return predicate.Locality(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Locality {
	return predicate.Locality(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Locality {
	return predicate.Locality(sql.FieldContainsFold(FieldName, v))
}

// ParentParishIDEQ applies the EQ predicate on the "parent_parish_id" field.
func ParentParishIDEQ(v uuid.UUID) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldParentParishID, v))
}

// ParentParishIDNEQ applies the NEQ predicate on the "parent_parish_id" field.
func ParentParishIDNEQ(v uuid.UUID) predicate.Locality {
	return predicate.Locality(sql.FieldNEQ(FieldParentParishID, v))
}

// ParentParishIDIn applies the In predicate on the "parent_parish_id" field.
func ParentParishIDIn(vs ...uuid.UUID) predicate.Locality {
	return predicate.Locality(sql.FieldIn(FieldParentParishID, vs...))
}

// ParentParishIDNotIn applies the NotIn predicate on the "parent_parish_id" field.
func ParentParishIDNotIn(vs ...uuid.UUID) predicate.Locality {
	return predicate.Locality(sql.FieldNotIn(FieldParentParishID, vs...))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Locality {
	return predicate.Locality(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Locality {
	return predicate.Locality(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Locality {
	return predicate.Locality(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Locality {
	return predicate.Locality(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Locality {
	return predicate.Locality(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Locality {
	return predicate.Locality(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Locality {
	return predicate.Locality(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Locality {
	return predicate.Locality(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Locality {
	return predicate.Locality(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Locality {
	return predicate.Locality(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Locality {
	return predicate.Locality(sql.FieldContainsFold(FieldSource, v))
}

// SourceElementIDEQ applies the EQ predicate on the "source_element_id" field.
func SourceElementIDEQ(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldSourceElementID, v))
}

// SourceElementIDNEQ applies the NEQ predicate on the "source_element_id" field.
func SourceElementIDNEQ(v string) predicate.Locality {
	return predicate.Locality(sql.FieldNEQ(FieldSourceElementID, v))
}

// SourceElementIDIn applies the In predicate on the "source_element_id" field.
func SourceElementIDIn(vs ...string) predicate.Locality {
	return predicate.Locality(sql.FieldIn(FieldSourceElementID, vs...))
}

// SourceElementIDNotIn applies the NotIn predicate on the "source_element_id" field.
func SourceElementIDNotIn(vs ...string) predicate.Locality {
	return predicate.Locality(sql.FieldNotIn(FieldSourceElementID, vs...))
}

// SourceElementIDGT applies the GT predicate on the "source_element_id" field.
func SourceElementIDGT(v string) predicate.Locality {
	return predicate.Locality(sql.FieldGT(FieldSourceElementID, v))
}

// SourceElementIDGTE applies the GTE predicate on the "source_element_id" field.
func SourceElementIDGTE(v string) predicate.Locality {
	return predicate.Locality(sql.FieldGTE(FieldSourceElementID, v))
}

// SourceElementIDLT applies the LT predicate on the "source_element_id" field.
func SourceElementIDLT(v string) predicate.Locality {
	return predicate.Locality(sql.FieldLT(FieldSourceElementID, v))
}

// SourceElementIDLTE applies the LTE predicate on the "source_element_id" field.
func SourceElementIDLTE(v string) predicate.Locality {
	return predicate.Locality(sql.FieldLTE(FieldSourceElementID, v))
}

// SourceElementIDContains applies the Contains predicate on the "source_element_id" field.
func SourceElementIDContains(v string) predicate.Locality {
	return predicate.Locality(sql.FieldContains(FieldSourceElementID, v))
}

// SourceElementIDHasPrefix applies the HasPrefix predicate on the "source_element_id" field.
func SourceElementIDHasPrefix(v string) predicate.Locality {
	return predicate.Locality(sql.FieldHasPrefix(FieldSourceElementID, v))
}

// SourceElementIDHasSuffix applies the HasSuffix predicate on the "source_element_id" field.
func SourceElementIDHasSuffix(v string) predicate.Locality {
	return predicate.Locality(sql.FieldHasSuffix(FieldSourceElementID, v))
}

// SourceElementIDEqualFold applies the EqualFold predicate on the "source_element_id" field.
func SourceElementIDEqualFold(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEqualFold(FieldSourceElementID, v))
}

// SourceElementIDContainsFold applies the ContainsFold predicate on the "source_element_id" field.
func SourceElementIDContainsFold(v string) predicate.Locality {
	return predicate.Locality(sql.FieldContainsFold(FieldSourceElementID, v))
}

// SourceVersionEQ applies the EQ predicate on the "source_version" field.
func SourceVersionEQ(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldSourceVersion, v))
}

// SourceVersionNEQ applies the NEQ predicate on the "source_version" field.
func SourceVersionNEQ(v string) predicate.Locality {
	return predicate.Locality(sql.FieldNEQ(FieldSourceVersion, v))
}

// SourceVersionIn applies the In predicate on the "source_version" field.
func SourceVersionIn(vs ...string) predicate.Locality {
	return predicate.Locality(sql.FieldIn(FieldSourceVersion, vs...))
}

// SourceVersionNotIn applies the NotIn predicate on the "source_version" field.
func SourceVersionNotIn(vs ...string) predicate.Locality {
	return predicate.Locality(sql.FieldNotIn(FieldSourceVersion, vs...))
}

// SourceVersionGT applies the GT predicate on the "source_version" field.
func SourceVersionGT(v string) predicate.Locality {
	return predicate.Locality(sql.FieldGT(FieldSourceVersion, v))
}

// SourceVersionGTE applies the GTE predicate on the "source_version" field.
func SourceVersionGTE(v string) predicate.Locality {
	return predicate.Locality(sql.FieldGTE(FieldSourceVersion, v))
}

// SourceVersionLT applies the LT predicate on the "source_version" field.
func SourceVersionLT(v string) predicate.Locality {
	return predicate.Locality(sql.FieldLT(FieldSourceVersion, v))
}

// SourceVersionLTE applies the LTE predicate on the "source_version" field.
func SourceVersionLTE(v string) predicate.Locality {
	return predicate.Locality(sql.FieldLTE(FieldSourceVersion, v))
}

// SourceVersionContains applies the Contains predicate on the "source_version" field.
func SourceVersionContains(v string) predicate.Locality {
	return predicate.Locality(sql.FieldContains(FieldSourceVersion, v))
}

// SourceVersionHasPrefix applies the HasPrefix predicate on the "source_version" field.
func SourceVersionHasPrefix(v string) predicate.Locality {
	return predicate.Locality(sql.FieldHasPrefix(FieldSourceVersion, v))
}

// SourceVersionHasSuffix applies the HasSuffix predicate on the "source_version" field.
func SourceVersionHasSuffix(v string) predicate.Locality {
	return predicate.Locality(sql.FieldHasSuffix(FieldSourceVersion, v))
}

// SourceVersionEqualFold applies the EqualFold predicate on the "source_version" field.
func SourceVersionEqualFold(v string) predicate.Locality {
	return predicate.Locality(sql.FieldEqualFold(FieldSourceVersion, v))
}

// SourceVersionContainsFold applies the ContainsFold predicate on the "source_version" field.
func SourceVersionContainsFold(v string) predicate.Locality {
	return predicate.Locality(sql.FieldContainsFold(FieldSourceVersion, v))
}

// SourceRetrievedAtEQ applies the EQ predicate on the "source_retrieved_at" field.
func SourceRetrievedAtEQ(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldSourceRetrievedAt, v))
}

// SourceRetrievedAtNEQ applies the NEQ predicate on the "source_retrieved_at" field.
func SourceRetrievedAtNEQ(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldNEQ(FieldSourceRetrievedAt, v))
}

// SourceRetrievedAtIn applies the In predicate on the "source_retrieved_at" field.
func SourceRetrievedAtIn(vs ...time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldIn(FieldSourceRetrievedAt, vs...))
}

// SourceRetrievedAtNotIn applies the NotIn predicate on the "source_retrieved_at" field.
func SourceRetrievedAtNotIn(vs ...time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldNotIn(FieldSourceRetrievedAt, vs...))
}

// SourceRetrievedAtGT applies the GT predicate on the "source_retrieved_at" field.
func SourceRetrievedAtGT(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldGT(FieldSourceRetrievedAt, v))
}

// SourceRetrievedAtGTE applies the GTE predicate on the "source_retrieved_at" field.
func SourceRetrievedAtGTE(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldGTE(FieldSourceRetrievedAt, v))
}

// SourceRetrievedAtLT applies the LT predicate on the "source_retrieved_at" field.
func SourceRetrievedAtLT(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldLT(FieldSourceRetrievedAt, v))
}

// SourceRetrievedAtLTE applies the LTE predicate on the "source_retrieved_at" field.
func SourceRetrievedAtLTE(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldLTE(FieldSourceRetrievedAt, v))
}

// LatitudeEQ applies the EQ predicate on the "latitude" field.
func LatitudeEQ(v float64) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldLatitude, v))
}

// LatitudeNEQ applies the NEQ predicate on the "latitude" field.
func LatitudeNEQ(v float64) predicate.Locality {
	return predicate.Locality(sql.FieldNEQ(FieldLatitude, v))
}

// LatitudeIn applies the In predicate on the "latitude" field.
func LatitudeIn(vs ...float64) predicate.Locality {
	return predicate.Locality(sql.FieldIn(FieldLatitude, vs...))
}

// LatitudeNotIn applies the NotIn predicate on the "latitude" field.
func LatitudeNotIn(vs ...float64) predicate.Locality {
	return predicate.Locality(sql.FieldNotIn(FieldLatitude, vs...))
}

// LatitudeGT applies the GT predicate on the "latitude" field.
func LatitudeGT(v float64) predicate.Locality {
	return predicate.Locality(sql.FieldGT(FieldLatitude, v))
}

// LatitudeGTE applies the GTE predicate on the "latitude" field.
func LatitudeGTE(v float64) predicate.Locality {
	return predicate.Locality(sql.FieldGTE(FieldLatitude, v))
}

// LatitudeLT applies the LT predicate on the "latitude" field.
func LatitudeLT(v float64) predicate.Locality {
	return predicate.Locality(sql.FieldLT(FieldLatitude, v))
}

// LatitudeLTE applies the LTE predicate on the "latitude" field.
func LatitudeLTE(v float64) predicate.Locality {
	return predicate.Locality(sql.FieldLTE(FieldLatitude, v))
}

// LongitudeEQ applies the EQ predicate on the "longitude" field.
func LongitudeEQ(v float64) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldLongitude, v))
}

// LongitudeNEQ applies the NEQ predicate on the "longitude" field.
func LongitudeNEQ(v float64) predicate.Locality {
	return predicate.Locality(sql.FieldNEQ(FieldLongitude, v))
}

// LongitudeIn applies the In predicate on the "longitude" field.
func LongitudeIn(vs ...float64) predicate.Locality {
	return predicate.Locality(sql.FieldIn(FieldLongitude, vs...))
}

// LongitudeNotIn applies the NotIn predicate on the "longitude" field.
func LongitudeNotIn(vs ...float64) predicate.Locality {
	return predicate.Locality(sql.FieldNotIn(FieldLongitude, vs...))
}

// LongitudeGT applies the GT predicate on the "longitude" field.
func LongitudeGT(v float64) predicate.Locality {
	return predicate.Locality(sql.FieldGT(FieldLongitude, v))
}

// LongitudeGTE applies the GTE predicate on the "longitude" field.
func LongitudeGTE(v float64) predicate.Locality {
	return predicate.Locality(sql.FieldGTE(FieldLongitude, v))
}

// LongitudeLT applies the LT predicate on the "longitude" field.
func LongitudeLT(v float64) predicate.Locality {
	return predicate.Locality(sql.FieldLT(FieldLongitude, v))
}

// LongitudeLTE applies the LTE predicate on the "longitude" field.
func LongitudeLTE(v float64) predicate.Locality {
	return predicate.Locality(sql.FieldLTE(FieldLongitude, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.Locality {
	return predicate.Locality(sql.FieldNEQ(FieldActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Locality {
	return predicate.Locality(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasParentParish applies the HasEdge predicate on the "parent_parish" edge.
func HasParentParish() predicate.Locality {
	return predicate.Locality(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentParishTable, ParentParishColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentParishWith applies the HasEdge predicate on the "parent_parish" edge with a given conditions (other predicates).
func HasParentParishWith(preds ...predicate.AdministrativeArea) predicate.Locality {
	return predicate.Locality(func(s *sql.Selector) {
		step := newParentParishStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProviderProfiles applies the HasEdge predicate on the "provider_profiles" edge.
func HasProviderProfiles() predicate.Locality {
	return predicate.Locality(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, ProviderProfilesTable, ProviderProfilesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderProfilesWith applies the HasEdge predicate on the "provider_profiles" edge with a given conditions (other predicates).
func HasProviderProfilesWith(preds ...predicate.ProviderProfile) predicate.Locality {
	return predicate.Locality(func(s *sql.Selector) {
		step := newProviderProfilesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Locality) predicate.Locality {
	return predicate.Locality(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Locality) predicate.Locality {
	return predicate.Locality(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Locality) predicate.Locality {
	return predicate.Locality(sql.NotPredicates(p))
}
