// Code generated by ent, DO NOT EDIT.

package providerservicelocality

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/predicate"
	"github.com/google/uuid"
)

// InternalUserID applies equality check predicate on the "internal_user_id" field. It's identical to InternalUserIDEQ.
func InternalUserID(v uuid.UUID) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(sql.FieldEQ(FieldInternalUserID, v))
}

// LocalityID applies equality check predicate on the "locality_id" field. It's identical to LocalityIDEQ.
func LocalityID(v uuid.UUID) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(sql.FieldEQ(FieldLocalityID, v))
}

// InternalUserIDEQ applies the EQ predicate on the "internal_user_id" field.
func InternalUserIDEQ(v uuid.UUID) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(sql.FieldEQ(FieldInternalUserID, v))
}

// InternalUserIDNEQ applies the NEQ predicate on the "internal_user_id" field.
func InternalUserIDNEQ(v uuid.UUID) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(sql.FieldNEQ(FieldInternalUserID, v))
}

// InternalUserIDIn applies the In predicate on the "internal_user_id" field.
func InternalUserIDIn(vs ...uuid.UUID) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(sql.FieldIn(FieldInternalUserID, vs...))
}

// InternalUserIDNotIn applies the NotIn predicate on the "internal_user_id" field.
func InternalUserIDNotIn(vs ...uuid.UUID) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(sql.FieldNotIn(FieldInternalUserID, vs...))
}

// LocalityIDEQ applies the EQ predicate on the "locality_id" field.
func LocalityIDEQ(v uuid.UUID) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(sql.FieldEQ(FieldLocalityID, v))
}

// LocalityIDNEQ applies the NEQ predicate on the "locality_id" field.
func LocalityIDNEQ(v uuid.UUID) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(sql.FieldNEQ(FieldLocalityID, v))
}

// LocalityIDIn applies the In predicate on the "locality_id" field.
func LocalityIDIn(vs ...uuid.UUID) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(sql.FieldIn(FieldLocalityID, vs...))
}

// LocalityIDNotIn applies the NotIn predicate on the "locality_id" field.
func LocalityIDNotIn(vs ...uuid.UUID) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(sql.FieldNotIn(FieldLocalityID, vs...))
}

// HasProfile applies the HasEdge predicate on the "profile" edge.
func HasProfile() predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, ProfileColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, ProfileTable, ProfileColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProfileWith applies the HasEdge predicate on the "profile" edge with a given conditions (other predicates).
func HasProfileWith(preds ...predicate.ProviderProfile) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(func(s *sql.Selector) {
		step := newProfileStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLocality applies the HasEdge predicate on the "locality" edge.
func HasLocality() predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, LocalityColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, LocalityTable, LocalityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLocalityWith applies the HasEdge predicate on the "locality" edge with a given conditions (other predicates).
func HasLocalityWith(preds ...predicate.Locality) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(func(s *sql.Selector) {
		step := newLocalityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProviderServiceLocality) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProviderServiceLocality) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProviderServiceLocality) predicate.ProviderServiceLocality {
	return predicate.ProviderServiceLocality(sql.NotPredicates(p))
}
