// Code generated by ent, DO NOT EDIT.

package internaluser

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldLTE(FieldID, id))
}

// ClerkSubject applies equality check predicate on the "clerk_subject" field. It's identical to ClerkSubjectEQ.
func ClerkSubject(v string) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldEQ(FieldClerkSubject, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldEQ(FieldUpdatedAt, v))
}

// ClerkSubjectEQ applies the EQ predicate on the "clerk_subject" field.
func ClerkSubjectEQ(v string) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldEQ(FieldClerkSubject, v))
}

// ClerkSubjectNEQ applies the NEQ predicate on the "clerk_subject" field.
func ClerkSubjectNEQ(v string) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldNEQ(FieldClerkSubject, v))
}

// ClerkSubjectIn applies the In predicate on the "clerk_subject" field.
func ClerkSubjectIn(vs ...string) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldIn(FieldClerkSubject, vs...))
}

// ClerkSubjectNotIn applies the NotIn predicate on the "clerk_subject" field.
func ClerkSubjectNotIn(vs ...string) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldNotIn(FieldClerkSubject, vs...))
}

// ClerkSubjectGT applies the GT predicate on the "clerk_subject" field.
func ClerkSubjectGT(v string) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldGT(FieldClerkSubject, v))
}

// ClerkSubjectGTE applies the GTE predicate on the "clerk_subject" field.
func ClerkSubjectGTE(v string) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldGTE(FieldClerkSubject, v))
}

// ClerkSubjectLT applies the LT predicate on the "clerk_subject" field.
func ClerkSubjectLT(v string) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldLT(FieldClerkSubject, v))
}

// ClerkSubjectLTE applies the LTE predicate on the "clerk_subject" field.
func ClerkSubjectLTE(v string) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldLTE(FieldClerkSubject, v))
}

// ClerkSubjectContains applies the Contains predicate on the "clerk_subject" field.
func ClerkSubjectContains(v string) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldContains(FieldClerkSubject, v))
}

// ClerkSubjectHasPrefix applies the HasPrefix predicate on the "clerk_subject" field.
func ClerkSubjectHasPrefix(v string) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldHasPrefix(FieldClerkSubject, v))
}

// ClerkSubjectHasSuffix applies the HasSuffix predicate on the "clerk_subject" field.
func ClerkSubjectHasSuffix(v string) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldHasSuffix(FieldClerkSubject, v))
}

// ClerkSubjectEqualFold applies the EqualFold predicate on the "clerk_subject" field.
func ClerkSubjectEqualFold(v string) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldEqualFold(FieldClerkSubject, v))
}

// ClerkSubjectContainsFold applies the ContainsFold predicate on the "clerk_subject" field.
func ClerkSubjectContainsFold(v string) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldContainsFold(FieldClerkSubject, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InternalUser {
	return predicate.InternalUser(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InternalUser) predicate.InternalUser {
	return predicate.InternalUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InternalUser) predicate.InternalUser {
	return predicate.InternalUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InternalUser) predicate.InternalUser {
	return predicate.InternalUser(sql.NotPredicates(p))
}
