// Code generated by ent, DO NOT EDIT.

package providerspokenlanguage

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the providerspokenlanguage type in the database.
	Label = "provider_spoken_language"
	// FieldInternalUserID holds the string denoting the internal_user_id field in the database.
	FieldInternalUserID = "internal_user_id"
	// FieldLanguageCode holds the string denoting the language_code field in the database.
	FieldLanguageCode = "language_code"
	// EdgeProfile holds the string denoting the profile edge name in mutations.
	EdgeProfile = "profile"
	// EdgeLanguage holds the string denoting the language edge name in mutations.
	EdgeLanguage = "language"
	// ProviderProfileFieldID holds the string denoting the ID field of the ProviderProfile.
	ProviderProfileFieldID = "internal_user_id"
	// SpokenLanguageFieldID holds the string denoting the ID field of the SpokenLanguage.
	SpokenLanguageFieldID = "id"
	// Table holds the table name of the providerspokenlanguage in the database.
	Table = "provider_spoken_languages"
	// ProfileTable is the table that holds the profile relation/edge.
	ProfileTable = "provider_spoken_languages"
	// ProfileInverseTable is the table name for the ProviderProfile entity.
	// It exists in this package in order to avoid circular dependency with the "providerprofile" package.
	ProfileInverseTable = "provider_profiles"
	// ProfileColumn is the table column denoting the profile relation/edge.
	ProfileColumn = "internal_user_id"
	// LanguageTable is the table that holds the language relation/edge.
	LanguageTable = "provider_spoken_languages"
	// LanguageInverseTable is the table name for the SpokenLanguage entity.
	// It exists in this package in order to avoid circular dependency with the "spokenlanguage" package.
	LanguageInverseTable = "spoken_languages"
	// LanguageColumn is the table column denoting the language relation/edge.
	LanguageColumn = "language_code"
)

// Columns holds all SQL columns for providerspokenlanguage fields.
var Columns = []string{
	FieldInternalUserID,
	FieldLanguageCode,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LanguageCodeValidator is a validator for the "language_code" field. It is called by the builders before save.
	LanguageCodeValidator func(string) error
)

// OrderOption defines the ordering options for the ProviderSpokenLanguage queries.
type OrderOption func(*sql.Selector)

// ByInternalUserID orders the results by the internal_user_id field.
func ByInternalUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInternalUserID, opts...).ToFunc()
}

// ByLanguageCode orders the results by the language_code field.
func ByLanguageCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguageCode, opts...).ToFunc()
}

// ByProfileField orders the results by profile field.
func ByProfileField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProfileStep(), sql.OrderByField(field, opts...))
	}
}

// ByLanguageField orders the results by language field.
func ByLanguageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLanguageStep(), sql.OrderByField(field, opts...))
	}
}
func newProfileStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, ProfileColumn),
		sqlgraph.To(ProfileInverseTable, ProviderProfileFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ProfileTable, ProfileColumn),
	)
}
func newLanguageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, LanguageColumn),
		sqlgraph.To(LanguageInverseTable, SpokenLanguageFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, LanguageTable, LanguageColumn),
	)
}
