// Code generated by ent, DO NOT EDIT.

package providercontactchannel

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the providercontactchannel type in the database.
	Label = "provider_contact_channel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInternalUserID holds the string denoting the internal_user_id field in the database.
	FieldInternalUserID = "internal_user_id"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldCiphertext holds the string denoting the ciphertext field in the database.
	FieldCiphertext = "ciphertext"
	// FieldNonce holds the string denoting the nonce field in the database.
	FieldNonce = "nonce"
	// FieldKeyVersion holds the string denoting the key_version field in the database.
	FieldKeyVersion = "key_version"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldRevealConsent holds the string denoting the reveal_consent field in the database.
	FieldRevealConsent = "reveal_consent"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the providercontactchannel in the database.
	Table = "provider_contact_channels"
)

// Columns holds all SQL columns for providercontactchannel fields.
var Columns = []string{
	FieldID,
	FieldInternalUserID,
	FieldChannel,
	FieldCiphertext,
	FieldNonce,
	FieldKeyVersion,
	FieldEnabled,
	FieldRevealConsent,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyVersionValidator is a validator for the "key_version" field. It is called by the builders before save.
	KeyVersionValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultRevealConsent holds the default value on creation for the "reveal_consent" field.
	DefaultRevealConsent bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Channel defines the type for the "channel" enum field.
type Channel string

// Channel values.
const (
	ChannelPhone    Channel = "phone"
	ChannelWhatsapp Channel = "whatsapp"
)

func (c Channel) String() string {
	return string(c)
}

// ChannelValidator is a validator for the "channel" field enum values. It is called by the builders before save.
func ChannelValidator(c Channel) error {
	switch c {
	case ChannelPhone, ChannelWhatsapp:
		return nil
	default:
		return fmt.Errorf("providercontactchannel: invalid enum value for channel field: %q", c)
	}
}

// OrderOption defines the ordering options for the ProviderContactChannel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInternalUserID orders the results by the internal_user_id field.
func ByInternalUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInternalUserID, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByKeyVersion orders the results by the key_version field.
func ByKeyVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyVersion, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByRevealConsent orders the results by the reveal_consent field.
func ByRevealConsent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevealConsent, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
