alter table public.notifications drop constraint notifications_kind;
alter table public.notifications add constraint notifications_kind check(kind in(
 'conversation_started','message_received','conversation_reported','request_published','proposal_received','proposal_accepted','proposal_rejected','booking_created','booking_updated','review_received','review_response','subscription_updated','promotion_updated'
));
create table public.marketplace_entitlement_defaults(id boolean primary key default true check(id),max_active_listings integer not null,max_photos_per_listing integer not null,analytics_enabled boolean not null default false,constraint entitlement_defaults_limits check(max_active_listings between 1 and 100 and max_photos_per_listing between 1 and 100));
insert into public.marketplace_entitlement_defaults(id,max_active_listings,max_photos_per_listing,analytics_enabled) values(true,3,5,false);
create table public.professional_plans(id uuid primary key default gen_random_uuid(),slug text not null unique,name text not null,price_minor integer not null,currency text not null default 'EUR',billing_days integer not null,max_active_listings integer not null,max_photos_per_listing integer not null,analytics_enabled boolean not null default false,active boolean not null default true,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()),constraint professional_plans_price check(price_minor>=0),constraint professional_plans_currency check(currency='EUR'),constraint professional_plans_billing check(billing_days between 1 and 366),constraint professional_plans_limits check(max_active_listings between 1 and 100 and max_photos_per_listing between 1 and 100));
create table public.promotion_periods(id uuid primary key default gen_random_uuid(),slug text not null unique,name text not null,duration_days integer not null,price_minor integer not null,currency text not null default 'EUR',active boolean not null default true,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()),constraint promotion_periods_duration check(duration_days between 1 and 90),constraint promotion_periods_price check(price_minor>=0),constraint promotion_periods_currency check(currency='EUR'));
create table public.provider_subscriptions(id uuid primary key default gen_random_uuid(),provider_internal_user_id uuid not null references public.provider_profiles(internal_user_id) on delete cascade,plan_id uuid not null references public.professional_plans(id) on delete restrict,status text not null,starts_at timestamptz,ends_at timestamptz,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()),constraint provider_subscriptions_status check(status in('pending','active','cancelled','expired')));
create unique index provider_subscriptions_current_idx on public.provider_subscriptions(provider_internal_user_id) where status in('pending','active');
create table public.listing_promotions(id uuid primary key default gen_random_uuid(),listing_id uuid not null references public.listings(id) on delete cascade,provider_internal_user_id uuid not null references public.provider_profiles(internal_user_id) on delete cascade,period_id uuid not null references public.promotion_periods(id) on delete restrict,status text not null,starts_at timestamptz,ends_at timestamptz,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()),constraint listing_promotions_status check(status in('pending','active','cancelled','expired')));
create unique index listing_promotions_current_idx on public.listing_promotions(listing_id) where status in('pending','active');create index listing_promotions_active_idx on public.listing_promotions(starts_at,ends_at,listing_id) where status='active';
