// Code generated by ent, DO NOT EDIT.

package listing

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/juntly/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldID, id))
}

// InternalUserID applies equality check predicate on the "internal_user_id" field. It's identical to InternalUserIDEQ.
func InternalUserID(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldInternalUserID, v))
}

// CategoryID applies equality check predicate on the "category_id" field. It's identical to CategoryIDEQ.
func CategoryID(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldCategoryID, v))
}

// PrimaryLocalityID applies equality check predicate on the "primary_locality_id" field. It's identical to PrimaryLocalityIDEQ.
func PrimaryLocalityID(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldPrimaryLocalityID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldDescription, v))
}

// PriceMinor applies equality check predicate on the "price_minor" field. It's identical to PriceMinorEQ.
func PriceMinor(v int) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldPriceMinor, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldCurrency, v))
}

// TravelsToCustomer applies equality check predicate on the "travels_to_customer" field. It's identical to TravelsToCustomerEQ.
func TravelsToCustomer(v bool) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldTravelsToCustomer, v))
}

// ReceivesCustomer applies equality check predicate on the "receives_customer" field. It's identical to ReceivesCustomerEQ.
func ReceivesCustomer(v bool) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldReceivesCustomer, v))
}

// RemoteServices applies equality check predicate on the "remote_services" field. It's identical to RemoteServicesEQ.
func RemoteServices(v bool) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldRemoteServices, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldRevision, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldUpdatedAt, v))
}

// InternalUserIDEQ applies the EQ predicate on the "internal_user_id" field.
func InternalUserIDEQ(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldInternalUserID, v))
}

// InternalUserIDNEQ applies the NEQ predicate on the "internal_user_id" field.
func InternalUserIDNEQ(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldInternalUserID, v))
}

// InternalUserIDIn applies the In predicate on the "internal_user_id" field.
func InternalUserIDIn(vs ...uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldInternalUserID, vs...))
}

// InternalUserIDNotIn applies the NotIn predicate on the "internal_user_id" field.
func InternalUserIDNotIn(vs ...uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldInternalUserID, vs...))
}

// InternalUserIDGT applies the GT predicate on the "internal_user_id" field.
func InternalUserIDGT(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldInternalUserID, v))
}

// InternalUserIDGTE applies the GTE predicate on the "internal_user_id" field.
func InternalUserIDGTE(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldInternalUserID, v))
}

// InternalUserIDLT applies the LT predicate on the "internal_user_id" field.
func InternalUserIDLT(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldInternalUserID, v))
}

// InternalUserIDLTE applies the LTE predicate on the "internal_user_id" field.
func InternalUserIDLTE(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldInternalUserID, v))
}

// CategoryIDEQ applies the EQ predicate on the "category_id" field.
func CategoryIDEQ(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldCategoryID, v))
}

// CategoryIDNEQ applies the NEQ predicate on the "category_id" field.
func CategoryIDNEQ(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldCategoryID, v))
}

// CategoryIDIn applies the In predicate on the "category_id" field.
func CategoryIDIn(vs ...uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldCategoryID, vs...))
}

// CategoryIDNotIn applies the NotIn predicate on the "category_id" field.
func CategoryIDNotIn(vs ...uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldCategoryID, vs...))
}

// CategoryIDGT applies the GT predicate on the "category_id" field.
func CategoryIDGT(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldCategoryID, v))
}

// CategoryIDGTE applies the GTE predicate on the "category_id" field.
func CategoryIDGTE(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldCategoryID, v))
}

// CategoryIDLT applies the LT predicate on the "category_id" field.
func CategoryIDLT(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldCategoryID, v))
}

// CategoryIDLTE applies the LTE predicate on the "category_id" field.
func CategoryIDLTE(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldCategoryID, v))
}

// PrimaryLocalityIDEQ applies the EQ predicate on the "primary_locality_id" field.
func PrimaryLocalityIDEQ(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldPrimaryLocalityID, v))
}

// PrimaryLocalityIDNEQ applies the NEQ predicate on the "primary_locality_id" field.
func PrimaryLocalityIDNEQ(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldPrimaryLocalityID, v))
}

// PrimaryLocalityIDIn applies the In predicate on the "primary_locality_id" field.
func PrimaryLocalityIDIn(vs ...uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldPrimaryLocalityID, vs...))
}

// PrimaryLocalityIDNotIn applies the NotIn predicate on the "primary_locality_id" field.
func PrimaryLocalityIDNotIn(vs ...uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldPrimaryLocalityID, vs...))
}

// PrimaryLocalityIDGT applies the GT predicate on the "primary_locality_id" field.
func PrimaryLocalityIDGT(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldPrimaryLocalityID, v))
}

// PrimaryLocalityIDGTE applies the GTE predicate on the "primary_locality_id" field.
func PrimaryLocalityIDGTE(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldPrimaryLocalityID, v))
}

// PrimaryLocalityIDLT applies the LT predicate on the "primary_locality_id" field.
func PrimaryLocalityIDLT(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldPrimaryLocalityID, v))
}

// PrimaryLocalityIDLTE applies the LTE predicate on the "primary_locality_id" field.
func PrimaryLocalityIDLTE(v uuid.UUID) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldPrimaryLocalityID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContainsFold(FieldDescription, v))
}

// PriceTypeEQ applies the EQ predicate on the "price_type" field.
func PriceTypeEQ(v PriceType) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldPriceType, v))
}

// PriceTypeNEQ applies the NEQ predicate on the "price_type" field.
func PriceTypeNEQ(v PriceType) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldPriceType, v))
}

// PriceTypeIn applies the In predicate on the "price_type" field.
func PriceTypeIn(vs ...PriceType) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldPriceType, vs...))
}

// PriceTypeNotIn applies the NotIn predicate on the "price_type" field.
func PriceTypeNotIn(vs ...PriceType) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldPriceType, vs...))
}

// PriceMinorEQ applies the EQ predicate on the "price_minor" field.
func PriceMinorEQ(v int) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldPriceMinor, v))
}

// PriceMinorNEQ applies the NEQ predicate on the "price_minor" field.
func PriceMinorNEQ(v int) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldPriceMinor, v))
}

// PriceMinorIn applies the In predicate on the "price_minor" field.
func PriceMinorIn(vs ...int) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldPriceMinor, vs...))
}

// PriceMinorNotIn applies the NotIn predicate on the "price_minor" field.
func PriceMinorNotIn(vs ...int) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldPriceMinor, vs...))
}

// PriceMinorGT applies the GT predicate on the "price_minor" field.
func PriceMinorGT(v int) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldPriceMinor, v))
}

// PriceMinorGTE applies the GTE predicate on the "price_minor" field.
func PriceMinorGTE(v int) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldPriceMinor, v))
}

// PriceMinorLT applies the LT predicate on the "price_minor" field.
func PriceMinorLT(v int) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldPriceMinor, v))
}

// PriceMinorLTE applies the LTE predicate on the "price_minor" field.
func PriceMinorLTE(v int) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldPriceMinor, v))
}

// PriceMinorIsNil applies the IsNil predicate on the "price_minor" field.
func PriceMinorIsNil() predicate.Listing {
	return predicate.Listing(sql.FieldIsNull(FieldPriceMinor))
}

// PriceMinorNotNil applies the NotNil predicate on the "price_minor" field.
func PriceMinorNotNil() predicate.Listing {
	return predicate.Listing(sql.FieldNotNull(FieldPriceMinor))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContainsFold(FieldCurrency, v))
}

// TravelsToCustomerEQ applies the EQ predicate on the "travels_to_customer" field.
func TravelsToCustomerEQ(v bool) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldTravelsToCustomer, v))
}

// TravelsToCustomerNEQ applies the NEQ predicate on the "travels_to_customer" field.
func TravelsToCustomerNEQ(v bool) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldTravelsToCustomer, v))
}

// ReceivesCustomerEQ applies the EQ predicate on the "receives_customer" field.
func ReceivesCustomerEQ(v bool) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldReceivesCustomer, v))
}

// ReceivesCustomerNEQ applies the NEQ predicate on the "receives_customer" field.
func ReceivesCustomerNEQ(v bool) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldReceivesCustomer, v))
}

// RemoteServicesEQ applies the EQ predicate on the "remote_services" field.
func RemoteServicesEQ(v bool) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldRemoteServices, v))
}

// RemoteServicesNEQ applies the NEQ predicate on the "remote_services" field.
func RemoteServicesNEQ(v bool) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldRemoteServices, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldState, vs...))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldRevision, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Listing) predicate.Listing {
	return predicate.Listing(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Listing) predicate.Listing {
	return predicate.Listing(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Listing) predicate.Listing {
	return predicate.Listing(sql.NotPredicates(p))
}
